# Generated by Django 5.2.17 on 2026-09-06 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('stdin', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('PENDING', 'Navbatda'), ('RUNNING', 'Tekshirilmoqda'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('PE', 'Presentation Error'), ('PARTIAL', 'Qisman ball'), ('IE', 'Internal Error'), ('SKIPPED', "O'tkazib yuborildi"), ('COMPILE_TIMEOUT', "Kompilyatsiya cho'zildi"), ('IDLENESS', 'Idleness Limit Exceeded'), ('SECURITY_VIOLATION', 'Xavfsizlik qoidasi buzildi'), ('CHECKER_ERROR', 'Checker xatosi'), ('TESTING_ABORTED', 'Tekshiruv bekor qilindi'), ('RATE_LIMITED', 'Submit limiti'), ('DENIAL_OF_JUDGEMENT', 'Infra nosozligi')], default='PENDING', max_length=24)),
                ('stdout', models.TextField(blank=True)),
                ('compile_output', models.TextField(blank=True)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('memory_kb', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_runs', to='problems.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
