# Generated by Django 5.2.17 on 2026-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_customrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='judge_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
