# Generated by Django 5.2.17 on 2026-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0003_attempt_judge_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='requeued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
