# Generated by Django 5.2.17 on 2026-09-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0005_alter_attempt_verdict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Navbatda'), ('RUNNING', 'Tekshirilmoqda'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RE', 'Runtime Error'), ('RE_SIGNAL', 'Runtime Error (signal)'), ('RE_EXIT', 'Runtime Error (chiqish kodi)'), ('CE', 'Compilation Error'), ('PE', 'Presentation Error'), ('HACKED', 'Hack qilindi'), ('PARTIAL', 'Qisman ball'), ('IE', 'Internal Error'), ('WRONG_TEST', 'Masala testi yaroqsiz'), ('SKIPPED', "O'tkazib yuborildi"), ('COMPILE_TIMEOUT', "Kompilyatsiya cho'zildi"), ('IDLENESS', 'Idleness Limit Exceeded'), ('SECURITY_VIOLATION', 'Xavfsizlik qoidasi buzildi'), ('CHECKER_ERROR', 'Checker xatosi'), ('TESTING_ABORTED', 'Tekshiruv bekor qilindi'), ('RATE_LIMITED', 'Submit limiti'), ('DENIAL_OF_JUDGEMENT', 'Infra nosozligi')], db_index=True, default='PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='attempttestresult',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Navbatda'), ('RUNNING', 'Tekshirilmoqda'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RE', 'Runtime Error'), ('RE_SIGNAL', 'Runtime Error (signal)'), ('RE_EXIT', 'Runtime Error (chiqish kodi)'), ('CE', 'Compilation Error'), ('PE', 'Presentation Error'), ('HACKED', 'Hack qilindi'), ('PARTIAL', 'Qisman ball'), ('IE', 'Internal Error'), ('WRONG_TEST', 'Masala testi yaroqsiz'), ('SKIPPED', "O'tkazib yuborildi"), ('COMPILE_TIMEOUT', "Kompilyatsiya cho'zildi"), ('IDLENESS', 'Idleness Limit Exceeded'), ('SECURITY_VIOLATION', 'Xavfsizlik qoidasi buzildi'), ('CHECKER_ERROR', 'Checker xatosi'), ('TESTING_ABORTED', 'Tekshiruv bekor qilindi'), ('RATE_LIMITED', 'Submit limiti'), ('DENIAL_OF_JUDGEMENT', 'Infra nosozligi')], max_length=24),
        ),
        migrations.AlterField(
            model_name='customrun',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Navbatda'), ('RUNNING', 'Tekshirilmoqda'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RE', 'Runtime Error'), ('RE_SIGNAL', 'Runtime Error (signal)'), ('RE_EXIT', 'Runtime Error (chiqish kodi)'), ('CE', 'Compilation Error'), ('PE', 'Presentation Error'), ('HACKED', 'Hack qilindi'), ('PARTIAL', 'Qisman ball'), ('IE', 'Internal Error'), ('WRONG_TEST', 'Masala testi yaroqsiz'), ('SKIPPED', "O'tkazib yuborildi"), ('COMPILE_TIMEOUT', "Kompilyatsiya cho'zildi"), ('IDLENESS', 'Idleness Limit Exceeded'), ('SECURITY_VIOLATION', 'Xavfsizlik qoidasi buzildi'), ('CHECKER_ERROR', 'Checker xatosi'), ('TESTING_ABORTED', 'Tekshiruv bekor qilindi'), ('RATE_LIMITED', 'Submit limiti'), ('DENIAL_OF_JUDGEMENT', 'Infra nosozligi')], default='PENDING', max_length=24),
        ),
    ]
