# Generated by hand — M10: tarixiy RE qatorlarni RE_SIGNAL/RE_EXIT ga ajratish.

from __future__ import annotations

from django.db import migrations

from judging.migrations._m10_heuristic import judge_meta_choice as _judge_meta_choice


def _relabel_re_legacy(apps, schema_editor) -> None:
    """Tarixiy RE qatorlarni RE_SIGNAL/RE_EXIT ga ajratish (M10).

    Jonli bazada o'lchandi (2026-09-29): `verdict='RE'` qatorlar soni
    **0** — hujjatlardagi 18 163 raqami joriy bazaga tegishli emas.
    Ya'ni migratsiya odatda hech narsani o'zgartirmaydi; boshqa muhit
    (staging/RESTORE qilingan eski dump) da esa quyidagi heuristika
    ishlaydi.
    """
    Attempt = apps.get_model("judging", "Attempt")

    pending = list(Attempt.objects.filter(verdict="RE").values_list("pk", flat=True))
    total = len(pending)
    if total == 0:
        print("M10: RE qatorlar topilmadi — hech narsa o'zgartirilmadi")
        return

    re_signal_count = 0
    re_exit_count = 0

    # Katta tranzaksiyalardan saqlanish uchun batch'lar bilan ishlaymiz
    batch_size = 1000
    for start in range(0, total, batch_size):
        batch_ids = pending[start : start + batch_size]
        for attempt in Attempt.objects.filter(pk__in=batch_ids).iterator():
            new_verdict = _judge_meta_choice(getattr(attempt, "judge_meta", None))
            if new_verdict == "RE_EXIT":
                re_exit_count += 1
            else:
                re_signal_count += 1
            Attempt.objects.filter(pk=attempt.pk).update(verdict=new_verdict)

    print(
        f"M10: {total} ta RE qator qayta yorliqlandi "
        f"(RE_SIGNAL: {re_signal_count}, RE_EXIT: {re_exit_count})"
    )


def _reverse_relabel(apps, schema_editor) -> None:
    """Teskari yo'nalish: RE_SIGNAL/RE_EXIT ni qayta RE ga birlashtirish.

    D11B: data migration'lar teskari yo'nalishda IE ga o'tkaziladi,
    chunki RE_SIGNAL/RE_EXIT ni qayta RE ga aylantirish ma'lumot
    yo'qotishiga olib boradi.
    """
    Attempt = apps.get_model("judging", "Attempt")
    affected = Attempt.objects.filter(verdict__in=("RE_SIGNAL", "RE_EXIT")).update(verdict="IE")
    print(f"M10 (reverse): {affected} ta qator IE ga o'tkazildi (RE_SIGNAL/RE_EXIT -> IE)")


class Migration(migrations.Migration):
    dependencies = [
        ("judging", "0007_attempt_scale_indexes"),
    ]

    operations = [
        migrations.RunPython(_relabel_re_legacy, _reverse_relabel),
    ]
