# Generated by hand — M10: tarixiy RE qatorlarni RE_SIGNAL/RE_EXIT ga ajratish.

from __future__ import annotations

from django.db import migrations


def _relabel_re_legacy(apps, schema_editor) -> None:
    """18 163 ta tarixiy RE qatorni RE_SIGNAL/RE_EXIT ga ajratish.

    Judge hozir RE_SIGNAL/RE_EXIT chiqaradi, lekin ajratishdan oldingi
    qatorlar bazada RE sifatida qolgan. Heuristik:

    - `details` JSON'da `signal` kaliti bo'lsa → RE_SIGNAL
    - `details` JSON'da `exit_code` kaliti bo'lsa → RE_EXIT
    - Aks holda → RE_SIGNAL (default, signal xatolar ko'proq uchragan)

    ``details`` maydoni barcha model'da yo'q (keyin qo'shilgan);
    mavjud bo'lmasa default RE_SIGNAL ishlatiladi.
    """
    Attempt = apps.get_model("judging", "Attempt")

    pending = list(Attempt.objects.filter(verdict="RE").values_list("pk", flat=True))
    total = len(pending)
    if total == 0:
        print("M10: RE qatorlar topilmadi — hech narsa o'zgartirilmadi")
        return

    re_signal_count = 0
    re_exit_count = 0

    # Katta tranzaksiyalardan saqlanish uchun batch'lar bilan ishlaymiz
    batch_size = 1000
    for start in range(0, total, batch_size):
        batch_ids = pending[start : start + batch_size]
        for attempt in Attempt.objects.filter(pk__in=batch_ids).iterator():
            details = getattr(attempt, "details", None) or {}
            if not isinstance(details, dict):
                details = {}

            if "signal" in details:
                new_verdict = "RE_SIGNAL"
                re_signal_count += 1
            elif "exit_code" in details:
                new_verdict = "RE_EXIT"
                re_exit_count += 1
            else:
                new_verdict = "RE_SIGNAL"
                re_signal_count += 1

            Attempt.objects.filter(pk=attempt.pk).update(verdict=new_verdict)

    print(
        f"M10: {total} ta RE qator qayta yorliqlandi "
        f"(RE_SIGNAL: {re_signal_count}, RE_EXIT: {re_exit_count})"
    )


def _reverse_relabel(apps, schema_editor) -> None:
    """Teskari yo'nalish: RE_SIGNAL/RE_EXIT ni qayta RE ga birlashtirish.

    D11B: data migration'lar teskari yo'nalishda IE ga o'tkaziladi,
    chunki RE_SIGNAL/RE_EXIT ni qayta RE ga aylantirish ma'lumot
    yo'qotishiga olib boradi.
    """
    Attempt = apps.get_model("judging", "Attempt")
    affected = Attempt.objects.filter(verdict__in=("RE_SIGNAL", "RE_EXIT")).update(
        verdict="IE"
    )
    print(f"M10 (reverse): {affected} ta qator IE ga o'tkazildi (RE_SIGNAL/RE_EXIT -> IE)")


class Migration(migrations.Migration):
    dependencies = [
        ("judging", "0007_attempt_scale_indexes"),
    ]

    operations = [
        migrations.RunPython(_relabel_re_legacy, _reverse_relabel),
    ]
