# Generated by Django 5.2.17 on 2026-09-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0009_attempt_running_test_index'),
        ('problems', '0028_package_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='problem_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='problems.problemrevision'),
        ),
    ]
