# Generated by Django 5.2.17 on 2026-10-07 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0010_package_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('carried', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='judging.attempt')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'order'), name='uniq_attempt_answer')],
            },
        ),
    ]
