# Generated by Django 5.2.17 on 2026-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
