# Generated by Django 5.2.17 on 2026-09-06 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Markdown: shartlar, mezonlar, sovrin')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('submission_deadline', models.DateTimeField()),
                ('end_at', models.DateTimeField(help_text="Natijalar e'lon qilinadigan vaqt")),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='HackathonSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Markdown')),
                ('repo_url', models.URLField()),
                ('demo_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='0–100', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hackathons.hackathon')),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('hackathon', 'user'), name='uniq_hackathon_entry')],
            },
        ),
    ]
