# Generated by Django 5.2.17 on 2026-09-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('locale', models.CharField(default='uz', max_length=2)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(help_text='Markdown + LaTeX')),
                ('locale', models.CharField(default='uz', max_length=2)),
                ('difficulty', models.PositiveIntegerField(default=800)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reading_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='articles', to='problems.topic')),
            ],
            options={
                'ordering': ['difficulty', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ArticleProblemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('practice', 'Mashq uchun'), ('example', 'Maqoladagi misol'), ('editorial', 'Yechim tushuntirishi')], default='practice', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='content.article')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_optional', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='content.article')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='problems.problem')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'difficulty'], name='article_browse'),
        ),
        migrations.AddConstraint(
            model_name='articleproblemlink',
            constraint=models.UniqueConstraint(fields=('article', 'problem', 'role'), name='uniq_article_problem_role'),
        ),
        migrations.AddConstraint(
            model_name='roadmapstep',
            constraint=models.UniqueConstraint(fields=('roadmap', 'order'), name='uniq_roadmap_order'),
        ),
    ]
