# Generated by Django 5.2.17 on 2026-09-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[('article', 'Maqola'), ('algorithm', 'Algoritm')], db_index=True, default='article', max_length=12),
        ),
    ]
