# Generated by Django 5.2.17 on 2026-09-06 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_entries', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standing',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='standing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(fields=('contest', 'index_letter'), name='uniq_contest_index'),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(fields=('contest', 'problem'), name='uniq_contest_problem'),
        ),
        migrations.AddConstraint(
            model_name='contestregistration',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='uniq_contest_registration'),
        ),
        migrations.AddIndex(
            model_name='standing',
            index=models.Index(fields=['contest', 'rank'], name='standing_board'),
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='uniq_contest_standing'),
        ),
    ]
