# Generated by Django 5.2.17 on 2026-09-11 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='jury',
            field=models.ManyToManyField(blank=True, related_name='jury_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
