# Generated by Django 5.2.17 on 2026-09-11 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_jury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('place', models.PositiveIntegerField()),
                ('participants', models.PositiveIntegerField()),
                ('tier', models.CharField(choices=[('gold', "1-o'rin"), ('silver', "2-o'rin"), ('bronze', "3-o'rin"), ('top10', 'Eng yaxshi 10%'), ('participant', 'Ishtirokchi')], max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'contest'), name='uniq_certificate')],
            },
        ),
    ]
