# Generated by Django 5.2.17 on 2026-09-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hack_open_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='hack_phase_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='hack_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='hack_tests_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='uphack_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='standing',
            name='hack_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='hacks_successful',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='hacks_unsuccessful',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
