# Generated by Django 5.2.17 on 2026-09-06 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rating_changed', "Reyting o'zgardi"), ('problem_rerated', 'Masala qayta baholandi'), ('contest_result', 'Musobaqa natijasi'), ('quest_awarded', 'Vazifa bajarildi'), ('streak_milestone', "Streak yutug'i"), ('system', 'Tizim')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('ref_type', models.CharField(blank=True, max_length=24)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notif_feed'), models.Index(fields=['user', 'read_at'], name='notif_unread')],
            },
        ),
    ]
