# Generated by Django 5.2.17 on 2026-09-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('rating_changed', "Reyting o'zgardi"), ('problem_rerated', 'Masala qayta baholandi'), ('contest_result', 'Musobaqa natijasi'), ('quest_awarded', 'Vazifa bajarildi'), ('streak_milestone', "Streak yutug'i"), ('duel', 'Duel'), ('hack', 'Hack'), ('system', 'Tizim')], max_length=24),
        ),
    ]
