# Generated by Django 5.2.17 on 2026-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_hack_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='notification',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
