# Generated by Django 5.2.17 on 2026-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_backfill_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprofile',
            name='kind',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('leetcode', 'LeetCode'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('x', 'X'), ('youtube', 'YouTube'), ('kaggle', 'Kaggle'), ('blog', 'Blog')], max_length=16),
        ),
    ]
