# Generated by Django 5.2.17 on 2026-09-19 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_current(apps, schema_editor):
    Education = apps.get_model("profiles", "Education")
    Work = apps.get_model("profiles", "WorkExperience")
    Education.objects.filter(end_year__isnull=True, start_year__isnull=False).update(current=True)
    Work.objects.filter(end_year__isnull=True, start_year__isnull=False).update(current=True)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_externalprofile_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.CreateModel(
            name="UserSkillBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=24)),
                ("icon", models.CharField(max_length=40)),
                ("color", models.CharField(default="#4f46e5", max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(mark_current, migrations.RunPython.noop),
    ]
