# Generated by Django 5.2.17 on 2026-10-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_settings_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('solved', 'Masala yechildi'), ('rating', "Reyting o'zgardi"), ('qvant', 'Qvant'), ('contest', 'Musobaqaga yozildi')], max_length=16)),
                ('ref_type', models.CharField(blank=True, max_length=24)),
                ('ref_id', models.CharField(blank=True, max_length=120)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_event_feed')],
            },
        ),
    ]
