# Generated by Django 5.2.17 on 2026-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_backfill_activity_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('solved', 'Masala yechildi'), ('rating', "Reyting o'zgardi"), ('qvant', 'Qvant'), ('contest', 'Musobaqaga yozildi'), ('quest', 'Vazifa bajarildi')], max_length=16),
        ),
    ]
