# Generated by Django 5.2.17 on 2026-10-05 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=80)),
                ('name_ru', models.CharField(blank=True, max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('core', 'Asosiy jamoa'), ('contributor', "Hissa qo'shgan")], default='contributor', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('context_uz', models.CharField(blank=True, max_length=200)),
                ('context_ru', models.CharField(blank=True, max_length=200)),
                ('context_en', models.CharField(blank=True, max_length=200)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('telegram_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('holds_all_roles', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('holds_all_roles', True)), fields=('holds_all_roles',), name='team_one_member_holds_all_roles')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('about_uz', models.CharField(max_length=300)),
                ('about_ru', models.CharField(blank=True, max_length=300)),
                ('about_en', models.CharField(blank=True, max_length=300)),
                ('reports_to_uz', models.CharField(blank=True, max_length=120)),
                ('reports_to_ru', models.CharField(blank=True, max_length=120)),
                ('reports_to_en', models.CharField(blank=True, max_length=120)),
                ('status_uz', models.CharField(blank=True, max_length=60)),
                ('status_ru', models.CharField(blank=True, max_length=60)),
                ('status_en', models.CharField(blank=True, max_length=60)),
                ('badge', models.CharField(blank=True, max_length=8)),
                ('hue', models.PositiveSmallIntegerField(default=262, validators=[django.core.validators.MaxValueValidator(359)])),
                ('tone', models.CharField(choices=[('ok', 'Yaxshi'), ('warn', 'Diqqat')], default='ok', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='team.department')),
            ],
            options={
                'ordering': ['department__order', 'order', 'pk'],
            },
        ),
    ]
