# Generated by Django 5.2.17 on 2026-09-06 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judging', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('skills', 'Skills'), ('contest', 'Contests'), ('activity', 'Activity'), ('challenges', 'Challenges')], max_length=16)),
                ('value_before', models.IntegerField()),
                ('value_after', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('problem_solved', 'Masala yechildi'), ('problem_rerated', 'Masala qayta baholandi'), ('contest', 'Musobaqa'), ('recalculation', 'Qayta hisoblash')], max_length=24)),
                ('ref_type', models.CharField(blank=True, max_length=24)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('seed', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'rating_type', '-created_at'], name='rating_hist_feed')],
            },
        ),
        migrations.CreateModel(
            name='UserSolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ac_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty_at_solve', models.PositiveIntegerField()),
                ('first_ac_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judging.attempt')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvers', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='solved_by_user'), models.Index(fields=['problem'], name='solved_by_problem')],
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='uniq_user_problem_solved')],
            },
        ),
    ]
