# Generated by Django 5.2.17 on 2026-09-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinghistory',
            name='reason',
            field=models.CharField(choices=[('problem_solved', 'Masala yechildi'), ('problem_rerated', 'Masala qayta baholandi'), ('contest', 'Musobaqa'), ('recalculation', 'Qayta hisoblash'), ('duel', 'Duel')], max_length=24),
        ),
    ]
