# Generated by Django 5.2.17 on 2026-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_uniq_email_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('password_reset', 'Parolni tiklash'), ('email_verify', 'Emailni tasdiqlash'), ('other', 'Boshqa')], default='other', max_length=24)),
                ('subject', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Yuborilmadi')], max_length=8)),
                ('attempts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_email', '-created_at'], name='core_emaild_to_emai_407b69_idx')],
            },
        ),
    ]
