# Generated by Django 5.2.17 on 2026-09-10 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_email_verified_at_emailverifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifytoken',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Tasdiqlash'), ('change', 'Almashtirish')], default='verify', max_length=8),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='picture',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='hidden_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Parolni tiklash'), ('email_verify', 'Emailni tasdiqlash'), ('email_changed', 'Pochta almashtirildi'), ('other', 'Boshqa')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('kaa', 'Qaraqalpaqsha'), ('ru', 'Русский'), ('en', 'English'), ('kk', 'Қазақша'), ('ky', 'Кыргызча'), ('tg', 'Тоҷикӣ'), ('tr', 'Türkçe'), ('zh', '中文'), ('es', 'Español')], default='uz', max_length=8),
        ),
        migrations.CreateModel(
            name='UsernameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(db_index=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
