# Generated by Django 5.2.17 on 2026-09-11 00:54

import core.models
from django.db import migrations, models


def hide_email(apps, schema_editor):
    """Mavjud hisoblar: pochta birinchi deploydan beri ochiq qolgan edi — yopiladi."""
    User = apps.get_model("core", "User")
    batch = []
    for user in User.objects.only("pk", "hidden_fields").iterator(chunk_size=2000):
        fields = list(user.hidden_fields or [])
        if "email" in fields:
            continue
        user.hidden_fields = sorted({*fields, "email"})
        batch.append(user)
        if len(batch) >= 1000:
            User.objects.bulk_update(batch, ["hidden_fields"])
            batch = []
    if batch:
        User.objects.bulk_update(batch, ["hidden_fields"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailverifytoken_purpose_socialaccount_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hidden_fields',
            field=models.JSONField(blank=True, default=core.models.default_hidden_fields),
        ),
        migrations.RunPython(hide_email, migrations.RunPython.noop),
    ]
