# Generated by Django 5.2.17 on 2026-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hide_email_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinned_achievements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
