# Generated by Django 5.2.17 on 2026-09-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_pinned_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('school', 'Maktab'), ('lyceum', 'Litsey'), ('university', 'Universitet'), ('other', 'Boshqa')], default='school', max_length=12)),
                ('country', models.CharField(default='UZ', max_length=2)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('district', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region', 'district'], name='school_place')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='school_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.school'),
        ),
    ]
