# Generated by Django 5.2.17 on 2026-09-13
#
# Rozilik maydonlari (qaror 13): shartlar (majburiy) + marketing (ixtiyoriy).
# Ikkalasi ham qo'shimcha — mavjud qatorlar `terms_accepted_at=NULL` va
# `marketing_opt_in=False` bo'lib qoladi, ya'ni hech kimga xat yuborilmaydi
# va eski hisoblar "rozilik bermagan" deb belgilanadi.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socialaccount_username_user_city_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
