# Generated by Django 5.2.17 on 2026-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_usernamehistory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Yuborildi"),
                    ("failed", "Yuborilmadi"),
                    ("skipped", "Yuborilmadi (zaxira domen)"),
                ],
                max_length=8,
            ),
        ),
    ]
