# Generated by Django 5.2.17 on 2026-09-18 13:54

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fill the new counters from their source tables (ADR-0024).

    The running code does not write these columns yet, so a bulk write
    cannot overwrite a concurrent update. Rows changed between this step and
    the new code going live are repaired by `manage.py recount_user_stats`.
    """
    from core.user_stats import reconcile

    reconcile(fix=True, registry=apps, bulk=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_emaildelivery_status"),
        ("judging", "0006_hacked_verdict"),
        ("ratings", "0002_alter_ratinghistory_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coach_can_view_attempts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="contribution",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="device_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="duel_ready_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="max_rating_activity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="max_rating_challenges",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="max_rating_contest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="max_rating_skills",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="message_min_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus"), ("pro", "Pro")],
                default="free",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_recipient",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_region",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="shirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("3XL", "3XL"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="solved_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_max",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
