# Generated by Django 5.2.17 on 2026-09-19 22:14

from django.db import migrations, models


def copy_website(apps, schema_editor):
    User = apps.get_model("core", "User")
    rows = list(User.objects.exclude(website="").only("pk", "website"))
    for row in rows:
        row.websites = [row.website]
    User.objects.bulk_update(rows, ["websites"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_user_rating_tier_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name_en",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not", "Prefer not to say"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_en",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_address_native",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_city_native",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_recipient_native",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_region_native",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="shirt_size_eu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("40", "40"),
                    ("42", "42"),
                    ("44", "44"),
                    ("46", "46"),
                    ("48", "48"),
                    ("50", "50"),
                    ("52", "52"),
                    ("54", "54"),
                    ("56", "56"),
                    ("58", "58"),
                    ("60", "60"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="websites",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_website, migrations.RunPython.noop),
    ]
