# Generated by Django 5.2.17 on 2026-09-19 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_settings_cards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteappearance",
            options={
                "verbose_name": "Default appearance",
                "verbose_name_plural": "Default appearance",
            },
        ),
    ]
