# Generated by Django 5.2.17 on 2026-09-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_rating_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='error', max_length=8)),
                ('scope', models.CharField(db_index=True, max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('release', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', '-created_at'], name='clientlog_scope_time')],
            },
        ),
    ]
