# Generated by Django 5.2.17 on 2026-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0028_backfill_origin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-rating_activity'], name='user_activity_desc'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-rating_challenges'], name='user_challenges_desc'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-streak_count'], name='user_streak_desc'),
        ),
    ]
