# Generated by Django 5.2.17 on 2026-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_home_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
