/** Mamlakat nomlari — o'zbek va rus tilida (ISO 3166-1 alpha-2).
 *
 * NEGA jadval kerak: `Intl.DisplayNames` bu Chrome'da o'zbekcha hudud
 * nomlarini BERMAYDI — inglizchaga tushadi ("Uzbekistan", "Kazakhstan"),
 * natijada o'zbekcha UI da inglizcha nom chiqardi va qidiruvda "qoz"
 * topilmasdi. Ruscha ishlaydi, lekin jadval ikkalasini bir xil qiladi.
 *
 * Nomlar Node'ning TO'LIQ ICU ma'lumotidan generatsiya qilingan
 * (`Intl.DisplayNames(["uz"])`), ya'ni qo'lda yozilgan emas.
 *
 * Boshqa tillar (en, tr, zh, es) uchun `Intl.DisplayNames` ishlaydi —
 * shuning uchun jadvalda faqat shu ikki til bor.
 */

export const COUNTRY_NAMES: Record<string, [uz: string, ru: string]> = {
  "AD": ["Andorra", "Андорра"],
  "AE": ["Birlashgan Arab Amirliklari", "ОАЭ"],
  "AF": ["Afgʻoniston", "Афганистан"],
  "AG": ["Antigua va Barbuda", "Антигуа и Барбуда"],
  "AI": ["Angilya", "Ангилья"],
  "AL": ["Albaniya", "Албания"],
  "AM": ["Armaniston", "Армения"],
  "AO": ["Angola", "Ангола"],
  "AQ": ["Antarktida", "Антарктида"],
  "AR": ["Argentina", "Аргентина"],
  "AS": ["Amerika Samoasi", "Американское Самоа"],
  "AT": ["Avstriya", "Австрия"],
  "AU": ["Avstraliya", "Австралия"],
  "AW": ["Aruba", "Аруба"],
  "AX": ["Aland orollari", "Аландские о-ва"],
  "AZ": ["Ozarbayjon", "Азербайджан"],
  "BA": ["Bosniya va Gertsegovina", "Босния и Герцеговина"],
  "BB": ["Barbados", "Барбадос"],
  "BD": ["Bangladesh", "Бангладеш"],
  "BE": ["Belgiya", "Бельгия"],
  "BF": ["Burkina-Faso", "Буркина-Фасо"],
  "BG": ["Bolgariya", "Болгария"],
  "BH": ["Bahrayn", "Бахрейн"],
  "BI": ["Burundi", "Бурунди"],
  "BJ": ["Benin", "Бенин"],
  "BL": ["Sen-Bartelemi", "Сен-Бартелеми"],
  "BM": ["Bermuda orollari", "Бермудские о-ва"],
  "BN": ["Bruney", "Бруней"],
  "BO": ["Boliviya", "Боливия"],
  "BQ": ["Boneyr, Sint-Estatius va Saba", "Бонэйр, Синт-Эстатиус и Саба"],
  "BR": ["Braziliya", "Бразилия"],
  "BS": ["Bagama orollari", "Багамы"],
  "BT": ["Butan", "Бутан"],
  "BV": ["Buve oroli", "о-в Буве"],
  "BW": ["Botsvana", "Ботсвана"],
  "BY": ["Belarus", "Беларусь"],
  "BZ": ["Beliz", "Белиз"],
  "CA": ["Kanada", "Канада"],
  "CC": ["Kokos (Kiling) orollari", "Кокосовые о-ва"],
  "CD": ["Kongo – Kinshasa", "Конго - Киншаса"],
  "CF": ["Markaziy Afrika Respublikasi", "Центрально-Африканская Республика"],
  "CG": ["Kongo – Brazzavil", "Конго - Браззавиль"],
  "CH": ["Shveytsariya", "Швейцария"],
  "CI": ["Kot-d’Ivuar", "Кот-д’Ивуар"],
  "CK": ["Kuk orollari", "о-ва Кука"],
  "CL": ["Chili", "Чили"],
  "CM": ["Kamerun", "Камерун"],
  "CN": ["Xitoy", "Китай"],
  "CO": ["Kolumbiya", "Колумбия"],
  "CR": ["Kosta-Rika", "Коста-Рика"],
  "CU": ["Kuba", "Куба"],
  "CV": ["Kabo-Verde", "Кабо-Верде"],
  "CW": ["Kyurasao", "Кюрасао"],
  "CX": ["Rojdestvo oroli", "о-в Рождества"],
  "CY": ["Kipr", "Кипр"],
  "CZ": ["Chexiya", "Чехия"],
  "DE": ["Germaniya", "Германия"],
  "DJ": ["Jibuti", "Джибути"],
  "DK": ["Daniya", "Дания"],
  "DM": ["Dominika", "Доминика"],
  "DO": ["Dominikan Respublikasi", "Доминиканская Республика"],
  "DZ": ["Jazoir", "Алжир"],
  "EC": ["Ekvador", "Эквадор"],
  "EE": ["Estoniya", "Эстония"],
  "EG": ["Misr", "Египет"],
  "EH": ["G‘arbiy Sahroi Kabir", "Западная Сахара"],
  "ER": ["Eritreya", "Эритрея"],
  "ES": ["Ispaniya", "Испания"],
  "ET": ["Efiopiya", "Эфиопия"],
  "FI": ["Finlandiya", "Финляндия"],
  "FJ": ["Fiji", "Фиджи"],
  "FK": ["Folklend orollari", "Фолклендские о-ва"],
  "FM": ["Mikroneziya", "Федеративные Штаты Микронезии"],
  "FO": ["Farer orollari", "Фарерские о-ва"],
  "FR": ["Fransiya", "Франция"],
  "GA": ["Gabon", "Габон"],
  "GB": ["Buyuk Britaniya", "Великобритания"],
  "GD": ["Grenada", "Гренада"],
  "GE": ["Gruziya", "Грузия"],
  "GF": ["Fransuz Gvianasi", "Французская Гвиана"],
  "GG": ["Gernsi", "Гернси"],
  "GH": ["Gana", "Гана"],
  "GI": ["Gibraltar", "Гибралтар"],
  "GL": ["Grenlandiya", "Гренландия"],
  "GM": ["Gambiya", "Гамбия"],
  "GN": ["Gvineya", "Гвинея"],
  "GP": ["Gvadelupe", "Гваделупа"],
  "GQ": ["Ekvatorial Gvineya", "Экваториальная Гвинея"],
  "GR": ["Gretsiya", "Греция"],
  "GS": ["Janubiy Georgiya va Janubiy Sendvich orollari", "Южная Георгия и Южные Сандвичевы о-ва"],
  "GT": ["Gvatemala", "Гватемала"],
  "GU": ["Guam", "Гуам"],
  "GW": ["Gvineya-Bisau", "Гвинея-Бисау"],
  "GY": ["Gayana", "Гайана"],
  "HK": ["Gonkong (Xitoy MMH)", "Гонконг (САР)"],
  "HM": ["Xerd va Makdonald orollari", "о-ва Херд и Макдональд"],
  "HN": ["Gonduras", "Гондурас"],
  "HR": ["Xorvatiya", "Хорватия"],
  "HT": ["Gaiti", "Гаити"],
  "HU": ["Vengriya", "Венгрия"],
  "ID": ["Indoneziya", "Индонезия"],
  "IE": ["Irlandiya", "Ирландия"],
  "IL": ["Isroil", "Израиль"],
  "IM": ["Men oroli", "о-в Мэн"],
  "IN": ["Hindiston", "Индия"],
  "IO": ["Britaniyaning Hind okeanidagi hududi", "Британская территория в Индийском океане"],
  "IQ": ["Iroq", "Ирак"],
  "IR": ["Eron", "Иран"],
  "IS": ["Islandiya", "Исландия"],
  "IT": ["Italiya", "Италия"],
  "JE": ["Jersi", "Джерси"],
  "JM": ["Yamayka", "Ямайка"],
  "JO": ["Iordaniya", "Иордания"],
  "JP": ["Yaponiya", "Япония"],
  "KE": ["Keniya", "Кения"],
  "KG": ["Qirgʻiziston", "Киргизия"],
  "KH": ["Kambodja", "Камбоджа"],
  "KI": ["Kiribati", "Кирибати"],
  "KM": ["Komor orollari", "Коморы"],
  "KN": ["Sent-Kits va Nevis", "Сент-Китс и Невис"],
  "KP": ["Shimoliy Koreya", "КНДР"],
  "KR": ["Janubiy Koreya", "Республика Корея"],
  "KW": ["Quvayt", "Кувейт"],
  "KY": ["Kayman orollari", "о-ва Кайман"],
  "KZ": ["Qozogʻiston", "Казахстан"],
  "LA": ["Laos", "Лаос"],
  "LB": ["Livan", "Ливан"],
  "LC": ["Sent-Lyusiya", "Сент-Люсия"],
  "LI": ["Lixtenshteyn", "Лихтенштейн"],
  "LK": ["Shri-Lanka", "Шри-Ланка"],
  "LR": ["Liberiya", "Либерия"],
  "LS": ["Lesoto", "Лесото"],
  "LT": ["Litva", "Литва"],
  "LU": ["Lyuksemburg", "Люксембург"],
  "LV": ["Latviya", "Латвия"],
  "LY": ["Liviya", "Ливия"],
  "MA": ["Marokash", "Марокко"],
  "MC": ["Monako", "Монако"],
  "MD": ["Moldova", "Молдова"],
  "ME": ["Chernogoriya", "Черногория"],
  "MF": ["Sent-Martin", "Сен-Мартен"],
  "MG": ["Madagaskar", "Мадагаскар"],
  "MH": ["Marshall orollari", "Маршалловы о-ва"],
  "MK": ["Shimoliy Makedoniya", "Северная Македония"],
  "ML": ["Mali", "Мали"],
  "MM": ["Myanma (Birma)", "Мьянма (Бирма)"],
  "MN": ["Mongoliya", "Монголия"],
  "MO": ["Makao (Xitoy MMH)", "Макао (САР)"],
  "MP": ["Shimoliy Mariana orollari", "Северные Марианские о-ва"],
  "MQ": ["Martinika", "Мартиника"],
  "MR": ["Mavritaniya", "Мавритания"],
  "MS": ["Montserrat", "Монтсеррат"],
  "MT": ["Malta", "Мальта"],
  "MU": ["Mavrikiy", "Маврикий"],
  "MV": ["Maldiv orollari", "Мальдивы"],
  "MW": ["Malavi", "Малави"],
  "MX": ["Meksika", "Мексика"],
  "MY": ["Malayziya", "Малайзия"],
  "MZ": ["Mozambik", "Мозамбик"],
  "NA": ["Namibiya", "Намибия"],
  "NC": ["Yangi Kaledoniya", "Новая Каледония"],
  "NE": ["Niger", "Нигер"],
  "NF": ["Norfolk oroli", "о-в Норфолк"],
  "NG": ["Nigeriya", "Нигерия"],
  "NI": ["Nikaragua", "Никарагуа"],
  "NL": ["Niderlandiya", "Нидерланды"],
  "NO": ["Norvegiya", "Норвегия"],
  "NP": ["Nepal", "Непал"],
  "NR": ["Nauru", "Науру"],
  "NU": ["Niue", "Ниуэ"],
  "NZ": ["Yangi Zelandiya", "Новая Зеландия"],
  "OM": ["Ummon", "Оман"],
  "PA": ["Panama", "Панама"],
  "PE": ["Peru", "Перу"],
  "PF": ["Fransuz Polineziyasi", "Французская Полинезия"],
  "PG": ["Papua – Yangi Gvineya", "Папуа — Новая Гвинея"],
  "PH": ["Filippin", "Филиппины"],
  "PK": ["Pokiston", "Пакистан"],
  "PL": ["Polsha", "Польша"],
  "PM": ["Sen-Pyer va Mikelon", "Сен-Пьер и Микелон"],
  "PN": ["Pitkern orollari", "о-ва Питкэрн"],
  "PR": ["Puerto-Riko", "Пуэрто-Рико"],
  "PS": ["Falastin hududlari", "Палестинские территории"],
  "PT": ["Portugaliya", "Португалия"],
  "PW": ["Palau", "Палау"],
  "PY": ["Paragvay", "Парагвай"],
  "QA": ["Qatar", "Катар"],
  "RE": ["Reyunion", "Реюньон"],
  "RO": ["Ruminiya", "Румыния"],
  "RS": ["Serbiya", "Сербия"],
  "RU": ["Rossiya", "Россия"],
  "RW": ["Ruanda", "Руанда"],
  "SA": ["Saudiya Arabistoni", "Саудовская Аравия"],
  "SB": ["Solomon orollari", "Соломоновы о-ва"],
  "SC": ["Seyshel orollari", "Сейшельские о-ва"],
  "SD": ["Sudan", "Судан"],
  "SE": ["Shvetsiya", "Швеция"],
  "SG": ["Singapur", "Сингапур"],
  "SH": ["Muqaddas Yelena oroli", "о-в Св. Елены"],
  "SI": ["Sloveniya", "Словения"],
  "SJ": ["Shpitsbergen va Yan-Mayen", "Шпицберген и Ян-Майен"],
  "SK": ["Slovakiya", "Словакия"],
  "SL": ["Syerra-Leone", "Сьерра-Леоне"],
  "SM": ["San-Marino", "Сан-Марино"],
  "SN": ["Senegal", "Сенегал"],
  "SO": ["Somali", "Сомали"],
  "SR": ["Surinam", "Суринам"],
  "SS": ["Janubiy Sudan", "Южный Судан"],
  "ST": ["San-Tome va Prinsipi", "Сан-Томе и Принсипи"],
  "SV": ["Salvador", "Сальвадор"],
  "SX": ["Sint-Marten", "Синт-Мартен"],
  "SY": ["Suriya", "Сирия"],
  "SZ": ["Svazilend", "Эсватини"],
  "TC": ["Turks va Kaykos orollari", "Тёркс и Кайкос"],
  "TD": ["Chad", "Чад"],
  "TF": ["Fransuz Janubiy hududlari", "Французские Южные территории"],
  "TG": ["Togo", "Того"],
  "TH": ["Tailand", "Таиланд"],
  "TJ": ["Tojikiston", "Таджикистан"],
  "TK": ["Tokelau", "Токелау"],
  "TL": ["Timor-Leste", "Восточный Тимор"],
  "TM": ["Turkmaniston", "Туркменистан"],
  "TN": ["Tunis", "Тунис"],
  "TO": ["Tonga", "Тонга"],
  "TR": ["Turkiya", "Турция"],
  "TT": ["Trinidad va Tobago", "Тринидад и Тобаго"],
  "TV": ["Tuvalu", "Тувалу"],
  "TW": ["Tayvan", "Тайвань"],
  "TZ": ["Tanzaniya", "Танзания"],
  "UA": ["Ukraina", "Украина"],
  "UG": ["Uganda", "Уганда"],
  "UM": ["AQSH yondosh orollari", "Внешние малые о-ва (США)"],
  "US": ["Amerika Qo‘shma Shtatlari", "Соединенные Штаты"],
  "UY": ["Urugvay", "Уругвай"],
  "UZ": ["Oʻzbekiston", "Узбекистан"],
  "VA": ["Vatikan", "Ватикан"],
  "VC": ["Sent-Vinsent va Grenadin", "Сент-Винсент и Гренадины"],
  "VE": ["Venesuela", "Венесуэла"],
  "VG": ["Britaniya Virgin orollari", "Виргинские о-ва (Великобритания)"],
  "VI": ["AQSH Virgin orollari", "Виргинские о-ва (США)"],
  "VN": ["Vyetnam", "Вьетнам"],
  "VU": ["Vanuatu", "Вануату"],
  "WF": ["Uollis va Futuna", "Уоллис и Футуна"],
  "WS": ["Samoa", "Самоа"],
  "YE": ["Yaman", "Йемен"],
  "YT": ["Mayotta", "Майотта"],
  "ZA": ["Janubiy Afrika Respublikasi", "Южно-Африканская Республика"],
  "ZM": ["Zambiya", "Замбия"],
  "ZW": ["Zimbabve", "Зимбабве"],
};
