# Generated by Django 5.2.17 on 2026-09-13 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Markdown')),
                ('locale', models.CharField(default='uz', max_length=5)),
                ('kind', models.CharField(choices=[('new', 'Yangi'), ('improved', 'Yaxshilandi'), ('fixed', 'Tuzatildi'), ('performance', 'Tezlik'), ('security', 'Xavfsizlik'), ('design', 'Dizayn'), ('content', 'Kontent'), ('infrastructure', 'Infratuzilma'), ('breaking', 'Buzuvchi'), ('deprecated', 'Olib tashlanadi')], db_index=True, max_length=16)),
                ('module', models.CharField(choices=[('problems', 'Masalalar'), ('contests', 'Musobaqalar'), ('arena', 'Bellashuvlar'), ('judge', 'Tekshiruv'), ('ratings', 'Reyting'), ('qvant', 'Qvant'), ('profile', 'Profil'), ('classroom', 'Sinf'), ('quizzes', 'Testlar'), ('content', 'Kontent'), ('design', 'Dizayn'), ('core', 'Umumiy')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan'), ('withdrawn', 'Nashrdan olingan')], db_index=True, default='draft', max_length=12)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('source_repo', models.CharField(blank=True, max_length=120)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('released_at', models.DateField(db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SystemUpdateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(db_index=True, max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Markdown')),
                ('is_machine', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='updates.systemupdate')),
            ],
            options={
                'ordering': ['locale'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='updates.systemupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='systemupdate',
            index=models.Index(fields=['status', 'is_enabled', '-released_at'], name='update_feed'),
        ),
        migrations.AddIndex(
            model_name='systemupdate',
            index=models.Index(fields=['module', '-released_at'], name='update_by_module'),
        ),
        migrations.AddIndex(
            model_name='systemupdate',
            index=models.Index(fields=['kind', '-released_at'], name='update_by_kind'),
        ),
        migrations.AddConstraint(
            model_name='systemupdatetranslation',
            constraint=models.UniqueConstraint(fields=('update', 'locale'), name='uniq_update_locale'),
        ),
        migrations.AddIndex(
            model_name='updateread',
            index=models.Index(fields=['user', '-read_at'], name='update_read_user'),
        ),
        migrations.AddConstraint(
            model_name='updateread',
            constraint=models.UniqueConstraint(fields=('user', 'update'), name='uniq_user_update_read'),
        ),
    ]
