"""What the team page starts with — written once by `0002_seed`.

After that the rows belong to the admin panel: this file is not read
again, and editing it changes nothing on a database that has the rows.
"""

from __future__ import annotations

from typing import Any

DEPARTMENTS: list[dict[str, Any]] = [
    {
        "name_uz": "Rahbariyat",
        "name_ru": "Руководство",
        "name_en": "Leadership",
        "order": 0,
    },
    {
        "name_uz": "Muhandislik",
        "name_ru": "Разработка",
        "name_en": "Engineering",
        "order": 1,
    },
    {
        "name_uz": "Dizayn",
        "name_ru": "Дизайн",
        "name_en": "Design",
        "order": 2,
    },
    {
        "name_uz": "Sifat",
        "name_ru": "Качество",
        "name_en": "Quality",
        "order": 3,
    },
    {
        "name_uz": "Infratuzilma",
        "name_ru": "Инфраструктура",
        "name_en": "Infrastructure",
        "order": 4,
    },
    {
        "name_uz": "Kontent",
        "name_ru": "Контент",
        "name_en": "Content",
        "order": 5,
    },
    {
        "name_uz": "Qo'llab-quvvatlash",
        "name_ru": "Поддержка",
        "name_en": "Support",
        "order": 6,
    },
    {
        "name_uz": "Marketing",
        "name_ru": "Маркетинг",
        "name_en": "Marketing",
        "order": 7,
    },
    {
        "name_uz": "Moliya",
        "name_ru": "Финансы",
        "name_en": "Finance",
        "order": 8,
    },
    {
        "name_uz": "Huquq",
        "name_ru": "Право",
        "name_en": "Legal",
        "order": 9,
    },
    {
        "name_uz": "Kadrlar",
        "name_ru": "Кадры",
        "name_en": "People",
        "order": 10,
    },
    {
        "name_uz": "Xo'jalik",
        "name_ru": "Хозяйство",
        "name_en": "Facilities",
        "order": 11,
    },
]

ROLES: list[dict[str, Any]] = [
    {
        "department": 0,
        "badge": "CEO",
        "hue": 262,
        "tone": "ok",
        "order": 0,
        "title_uz": "Asoschi va bosh direktor",
        "about_uz": "Strategiyani belgilaydi. Strategiya: «bugun ham ishlaymiz».",
        "reports_to_uz": "Vijdoniga",
        "status_uz": "Ofisda",
        "title_ru": "Основатель и генеральный директор",
        "about_ru": "Определяет стратегию. Стратегия: «сегодня тоже работаем».",
        "reports_to_ru": "Совести",
        "status_ru": "В офисе",
        "title_en": "Founder and CEO",
        "about_en": "Sets the strategy. The strategy: “we work today as well”.",
        "reports_to_en": "His conscience",
        "status_en": "In the office",
    },
    {
        "department": 0,
        "badge": "x1",
        "hue": 250,
        "tone": "ok",
        "order": 1,
        "title_uz": "Direktorlar kengashi raisi",
        "about_uz": "Kengash yig'ilishlarida yagona ovoz bilan qaror qabul qiladi.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Kvorum bor",
        "title_ru": "Председатель совета директоров",
        "about_ru": "На заседаниях совета принимает решения единогласно.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Кворум есть",
        "title_en": "Chair of the board",
        "about_en": "Decides unanimously at every board meeting.",
        "reports_to_en": "The CEO",
        "status_en": "Quorum reached",
    },
    {
        "department": 1,
        "badge": "CTO",
        "hue": 215,
        "tone": "warn",
        "order": 0,
        "title_uz": "Bosh texnik direktor",
        "about_uz": "Arxitektura qarorlarini qabul qiladi va keyin o'zi bilan bahslashadi.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "O'zi bilan review'da",
        "title_ru": "Технический директор",
        "about_ru": "Принимает архитектурные решения, а потом спорит сам с собой.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "На ревью у себя",
        "title_en": "Chief technology officer",
        "about_en": "Makes the architecture decisions, then argues with himself.",
        "reports_to_en": "The CEO",
        "status_en": "In review with himself",
    },
    {
        "department": 1,
        "badge": "API",
        "hue": 200,
        "tone": "ok",
        "order": 1,
        "title_uz": "Backend dasturchi",
        "about_uz": "Django, Celery va 3 soat davomida bitta vergul qidirish bo'yicha mutaxassis.",
        "reports_to_uz": "Bosh texnik direktorga",
        "status_uz": "Kod yozmoqda",
        "title_ru": "Бэкенд-разработчик",
        "about_ru": "Специалист по Django, Celery и трёхчасовому поиску одной запятой.",
        "reports_to_ru": "Техническому директору",
        "status_ru": "Пишет код",
        "title_en": "Backend developer",
        "about_en": "Expert in Django, Celery and three-hour searches for one comma.",
        "reports_to_en": "The CTO",
        "status_en": "Writing code",
    },
    {
        "department": 1,
        "badge": "</>",
        "hue": 190,
        "tone": "ok",
        "order": 2,
        "title_uz": "Frontend dasturchi",
        "about_uz": "Tugmani 2 piksel chapga suradi. Keyin yana o'ngga.",
        "reports_to_uz": "Bosh texnik direktorga",
        "status_uz": "Kod yozmoqda",
        "title_ru": "Фронтенд-разработчик",
        "about_ru": "Двигает кнопку на 2 пикселя влево. Потом обратно вправо.",
        "reports_to_ru": "Техническому директору",
        "status_ru": "Пишет код",
        "title_en": "Frontend developer",
        "about_en": "Moves a button 2 pixels left. Then back to the right.",
        "reports_to_en": "The CTO",
        "status_en": "Writing code",
    },
    {
        "department": 1,
        "badge": "AC",
        "hue": 140,
        "tone": "ok",
        "order": 3,
        "title_uz": "Judge muhandisi",
        "about_uz": "Sandbox ichida boshqalarning kodini, tashqarisida o'zinikini jazolaydi.",
        "reports_to_uz": "Bosh texnik direktorga",
        "status_uz": "Accepted",
        "title_ru": "Инженер judge",
        "about_ru": "В песочнице наказывает чужой код, снаружи — свой.",
        "reports_to_ru": "Техническому директору",
        "status_ru": "Accepted",
        "title_en": "Judge engineer",
        "about_en": "Punishes other people's code in the sandbox and his own outside it.",
        "reports_to_en": "The CTO",
        "status_en": "Accepted",
    },
    {
        "department": 1,
        "badge": "LGTM",
        "hue": 170,
        "tone": "ok",
        "order": 4,
        "title_uz": "Kod sharhlovchi",
        "about_uz": "Har bir PR'ni sinchiklab o'qiydi. Muallifi tanish chiqadi.",
        "reports_to_uz": "Backend dasturchiga",
        "status_uz": "Tasdiqladi",
        "title_ru": "Ревьюер кода",
        "about_ru": "Внимательно читает каждый PR. Автор оказывается знакомым.",
        "reports_to_ru": "Бэкенд-разработчику",
        "status_ru": "Одобрил",
        "title_en": "Code reviewer",
        "about_en": "Reads every pull request carefully. The author turns out to be familiar.",
        "reports_to_en": "The backend developer",
        "status_en": "Approved",
    },
    {
        "department": 2,
        "badge": "UI",
        "hue": 320,
        "tone": "warn",
        "order": 0,
        "title_uz": "Bosh dizayner",
        "about_uz": "12 ta uslub chizdi, chunki bittasini tanlay olmadi.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Rang tanlamoqda",
        "title_ru": "Главный дизайнер",
        "about_ru": "Нарисовал 12 стилей, потому что не смог выбрать один.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Выбирает цвет",
        "title_en": "Head of design",
        "about_en": "Drew 12 styles because he could not pick one.",
        "reports_to_en": "The CEO",
        "status_en": "Choosing a colour",
    },
    {
        "department": 2,
        "badge": "UX",
        "hue": 300,
        "tone": "ok",
        "order": 1,
        "title_uz": "UX tadqiqotchi",
        "about_uz": "Foydalanuvchilar bilan suhbat o'tkazadi. Suhbatdosh doim rozi bo'ladi.",
        "reports_to_uz": "Bosh dizaynerga",
        "status_uz": "Intervyu o'tkazmoqda",
        "title_ru": "UX-исследователь",
        "about_ru": "Проводит интервью с пользователями. Собеседник всегда согласен.",
        "reports_to_ru": "Главному дизайнеру",
        "status_ru": "Берёт интервью",
        "title_en": "UX researcher",
        "about_en": "Interviews users. The interviewee always agrees.",
        "reports_to_en": "The head of design",
        "status_en": "Running an interview",
    },
    {
        "department": 3,
        "badge": "QA",
        "hue": 20,
        "tone": "warn",
        "order": 0,
        "title_uz": "QA muhandisi",
        "about_uz": "Dasturchi «menda ishlayapti» desa, ishonmaydi. To'g'ri qiladi.",
        "reports_to_uz": "Bosh texnik direktorga",
        "status_uz": "Bug topdi",
        "title_ru": "QA-инженер",
        "about_ru": "Не верит разработчику, когда тот говорит «у меня работает». И правильно.",
        "reports_to_ru": "Техническому директору",
        "status_ru": "Нашёл баг",
        "title_en": "QA engineer",
        "about_en": "Does not believe a developer who says “works on my machine”. Rightly.",
        "reports_to_en": "The CTO",
        "status_en": "Found a bug",
    },
    {
        "department": 3,
        "badge": "!ok",
        "hue": 0,
        "tone": "ok",
        "order": 1,
        "title_uz": "Salbiy testlar bo'yicha mutaxassis",
        "about_uz": "Hamma narsani ataylab buzadi va buzilganidan xursand bo'ladi.",
        "reports_to_uz": "QA muhandisiga",
        "status_uz": "Qizil = yaxshi",
        "title_ru": "Специалист по негативным тестам",
        "about_ru": "Нарочно всё ломает и радуется, когда сломалось.",
        "reports_to_ru": "QA-инженеру",
        "status_ru": "Красное = хорошо",
        "title_en": "Negative-test specialist",
        "about_en": "Breaks everything on purpose and is glad when it breaks.",
        "reports_to_en": "The QA engineer",
        "status_en": "Red = good",
    },
    {
        "department": 4,
        "badge": "CI",
        "hue": 95,
        "tone": "ok",
        "order": 0,
        "title_uz": "DevOps muhandisi",
        "about_uz": "Deploy tugmasini bosadi va nafasini ichiga yutadi.",
        "reports_to_uz": "Bosh texnik direktorga",
        "status_uz": "CI yashil",
        "title_ru": "DevOps-инженер",
        "about_ru": "Нажимает кнопку деплоя и задерживает дыхание.",
        "reports_to_ru": "Техническому директору",
        "status_ru": "CI зелёный",
        "title_en": "DevOps engineer",
        "about_en": "Presses the deploy button and holds his breath.",
        "reports_to_en": "The CTO",
        "status_en": "CI green",
    },
    {
        "department": 4,
        "badge": "02:00",
        "hue": 240,
        "tone": "warn",
        "order": 1,
        "title_uz": "Tungi navbatchi",
        "about_uz": "Soat ikkida uyg'onadi. Kim uyg'otgani ma'lum.",
        "reports_to_uz": "DevOps muhandisiga",
        "status_uz": "Uyqusiz",
        "title_ru": "Ночной дежурный",
        "about_ru": "Просыпается в два часа ночи. Известно, кто разбудил.",
        "reports_to_ru": "DevOps-инженеру",
        "status_ru": "Не спал",
        "title_en": "Night on-call",
        "about_en": "Wakes up at two in the morning. It is known who woke him.",
        "reports_to_en": "The DevOps engineer",
        "status_en": "No sleep",
    },
    {
        "department": 4,
        "badge": "SQL",
        "hue": 205,
        "tone": "ok",
        "order": 2,
        "title_uz": "Ma'lumotlar bazasi ma'muri",
        "about_uz": "Indeks qo'shadi. Zaxira nusxa oladi. Yaxshi uxlaydi (nazariy jihatdan).",
        "reports_to_uz": "DevOps muhandisiga",
        "status_uz": "Zaxira bor",
        "title_ru": "Администратор баз данных",
        "about_ru": "Добавляет индекс. Делает бэкап. Спит спокойно (в теории).",
        "reports_to_ru": "DevOps-инженеру",
        "status_ru": "Бэкап есть",
        "title_en": "Database administrator",
        "about_en": "Adds an index. Takes a backup. Sleeps well (in theory).",
        "reports_to_en": "The DevOps engineer",
        "status_en": "Backup exists",
    },
    {
        "department": 5,
        "badge": "A+B",
        "hue": 38,
        "tone": "ok",
        "order": 0,
        "title_uz": "Masalalar muallifi",
        "about_uz": "A + B dan boshladi. Hozircha A + B da.",
        "reports_to_uz": "Kontent rahbariga",
        "status_uz": "Yozmoqda",
        "title_ru": "Автор задач",
        "about_ru": "Начал с A + B. Пока на A + B.",
        "reports_to_ru": "Руководителю контента",
        "status_ru": "Пишет",
        "title_en": "Problem setter",
        "about_en": "Started with A + B. Still on A + B.",
        "reports_to_en": "The head of content",
        "status_en": "Writing",
    },
    {
        "department": 5,
        "badge": "Aa",
        "hue": 52,
        "tone": "warn",
        "order": 1,
        "title_uz": "Kontent rahbari",
        "about_uz": "Masalalar muallifidan muddatni so'raydi. Javob oladi: «ertaga».",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Muddat yaqin",
        "title_ru": "Руководитель контента",
        "about_ru": "Спрашивает у автора задач о сроках. Получает ответ: «завтра».",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Срок близко",
        "title_en": "Head of content",
        "about_en": "Asks the problem setter for a deadline. Gets the answer: “tomorrow”.",
        "reports_to_en": "The CEO",
        "status_en": "Deadline close",
    },
    {
        "department": 5,
        "badge": "10",
        "hue": 170,
        "tone": "warn",
        "order": 2,
        "title_uz": "Tarjimon (10 til)",
        "about_uz": "O'zbekchani biladi. Qolgan to'qqiztasini tekshirib ko'rishga va'da bergan.",
        "reports_to_uz": "Kontent rahbariga",
        "status_uz": "Ko'rib chiqilmagan",
        "title_ru": "Переводчик (10 языков)",
        "about_ru": "Знает узбекский. Остальные девять обещал проверить.",
        "reports_to_ru": "Руководителю контента",
        "status_ru": "Не проверено",
        "title_en": "Translator (10 languages)",
        "about_en": "Knows Uzbek. Has promised to check the other nine.",
        "reports_to_en": "The head of content",
        "status_en": "Not reviewed",
    },
    {
        "department": 6,
        "badge": "24/7",
        "hue": 345,
        "tone": "ok",
        "order": 0,
        "title_uz": "Qo'llab-quvvatlash xizmati",
        "about_uz": "Murojaatlarga 24/7 javob beradi, uxlagan paytidan tashqari.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Onlayn",
        "title_ru": "Служба поддержки",
        "about_ru": "Отвечает на обращения 24/7, кроме времени сна.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Онлайн",
        "title_en": "Support",
        "about_en": "Answers requests 24/7, except while asleep.",
        "reports_to_en": "The CEO",
        "status_en": "Online",
    },
    {
        "department": 7,
        "badge": "CMO",
        "hue": 290,
        "tone": "ok",
        "order": 0,
        "title_uz": "Marketing direktori",
        "about_uz": "Reklama byudjeti: 0 so'm. Samaradorlik: cheksiz.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Kampaniya ketmoqda",
        "title_ru": "Директор по маркетингу",
        "about_ru": "Рекламный бюджет: 0 сумов. Эффективность: бесконечная.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Кампания идёт",
        "title_en": "Chief marketing officer",
        "about_en": "Advertising budget: 0 soums. Efficiency: infinite.",
        "reports_to_en": "The CEO",
        "status_en": "Campaign running",
    },
    {
        "department": 7,
        "badge": "@",
        "hue": 330,
        "tone": "ok",
        "order": 1,
        "title_uz": "SMM menejeri",
        "about_uz": "Kanalga post yozadi va birinchi bo'lib o'zi layk bosadi.",
        "reports_to_uz": "Marketing direktoriga",
        "status_uz": "1 ta layk",
        "title_ru": "SMM-менеджер",
        "about_ru": "Пишет пост в канал и первым ставит лайк.",
        "reports_to_ru": "Директору по маркетингу",
        "status_ru": "1 лайк",
        "title_en": "Social media manager",
        "about_en": "Posts to the channel and is the first to like it.",
        "reports_to_en": "The CMO",
        "status_en": "1 like",
    },
    {
        "department": 8,
        "badge": "CFO",
        "hue": 150,
        "tone": "ok",
        "order": 0,
        "title_uz": "Moliya direktori",
        "about_uz": "Xarajatlarni tasdiqlaydi: server, domen va choy.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Byudjet ichida",
        "title_ru": "Финансовый директор",
        "about_ru": "Утверждает расходы: сервер, домен и чай.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "В рамках бюджета",
        "title_en": "Chief financial officer",
        "about_en": "Approves the expenses: server, domain and tea.",
        "reports_to_en": "The CEO",
        "status_en": "Within budget",
    },
    {
        "department": 9,
        "badge": "§",
        "hue": 225,
        "tone": "ok",
        "order": 0,
        "title_uz": "Yurist",
        "about_uz": "Foydalanish shartlarini yozdi. Hatto o'zi ham o'qib chiqdi.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Shartlar yozilgan",
        "title_ru": "Юрист",
        "about_ru": "Написал условия использования. И даже сам их прочитал.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Условия написаны",
        "title_en": "Lawyer",
        "about_en": "Wrote the terms of use. And even read them himself.",
        "reports_to_en": "The CEO",
        "status_en": "Terms written",
    },
    {
        "department": 10,
        "badge": "HR",
        "hue": 310,
        "tone": "ok",
        "order": 0,
        "title_uz": "Kadrlar bo'limi boshlig'i",
        "about_uz": "Yil xodimini aniqladi. Nomzodlar ro'yxati qisqa edi.",
        "reports_to_uz": "Bosh direktorga",
        "status_uz": "Jamoa ruhi a'lo",
        "title_ru": "Начальник отдела кадров",
        "about_ru": "Определил сотрудника года. Список кандидатов был коротким.",
        "reports_to_ru": "Генеральному директору",
        "status_ru": "Командный дух отличный",
        "title_en": "Head of people",
        "about_en": "Named the employee of the year. The shortlist was short.",
        "reports_to_en": "The CEO",
        "status_en": "Team spirit excellent",
    },
    {
        "department": 11,
        "badge": "choy",
        "hue": 30,
        "tone": "ok",
        "order": 0,
        "title_uz": "Choy damlovchi",
        "about_uz": "Eng muhim lavozim. Butun ishlab chiqarish shu kishiga bog'liq.",
        "reports_to_uz": "Hammaga",
        "status_uz": "Qaynayapti",
        "title_ru": "Заваривающий чай",
        "about_ru": "Самая важная должность. От неё зависит всё производство.",
        "reports_to_ru": "Всем",
        "status_ru": "Закипает",
        "title_en": "Tea maker",
        "about_en": "The most important role. All production depends on it.",
        "reports_to_en": "Everyone",
        "status_en": "Boiling",
    },
]

FOUNDER: dict[str, Any] = {
    "section": "core",
    "name": "Saidakbar Narzullayev",
    "title_uz": "Asoschi va yagona ishlab chiquvchi",
    "title_ru": "Основатель и единственный разработчик",
    "title_en": "Founder and only developer",
    "photo_url": "/team/saidakbar.jpg",
    "telegram_url": "https://t.me/rankwant",
    "github_url": "https://github.com/menarzullayev",
    "holds_all_roles": True,
    "order": 0,
}
