# Generated by Django 5.2.17 on 2026-09-13 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Markdown')),
                ('status', models.CharField(choices=[('suggested', "Ko'rib chiqilmoqda"), ('planned', 'Rejalashtirilgan'), ('in_progress', 'Ishlanmoqda'), ('released', 'Chiqarildi'), ('declined', 'Rad etilgan')], db_index=True, default='suggested', max_length=12)),
                ('target_quarter', models.CharField(blank=True, max_length=24)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to='updates.systemupdate')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_comments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roadmap.roadmapitem')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='roadmap.roadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='roadmapitem',
            index=models.Index(fields=['status', 'is_enabled', '-created_at'], name='roadmap_feed'),
        ),
        migrations.AddIndex(
            model_name='roadmapcomment',
            index=models.Index(fields=['item', 'is_hidden', 'created_at'], name='roadmap_comment_feed'),
        ),
        migrations.AddIndex(
            model_name='roadmapvote',
            index=models.Index(fields=['user', '-created_at'], name='roadmap_vote_user'),
        ),
        migrations.AddConstraint(
            model_name='roadmapvote',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='uniq_roadmap_vote'),
        ),
    ]
