# Generated by Django 5.2.17 on 2026-09-15 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0005_hack_windows'),
        ('judging', '0006_hacked_verdict'),
        ('problems', '0015_reference_solution_and_test_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='contests.contest')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='HackRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_members', to='contests.contest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hacks.hackroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hack_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(choices=[('contest_room', 'Musobaqa xonasi'), ('open_phase', 'Ochiq faza'), ('practice', 'Amaliyot'), ('uphack', 'Uphack')], max_length=16)),
                ('status', models.CharField(choices=[('TESTING', 'Tekshirilmoqda'), ('SUCCESSFUL', 'Muvaffaqiyatli'), ('UNSUCCESSFUL', 'Muvaffaqiyatsiz'), ('INVALID_INPUT', 'Kiritma yaroqsiz'), ('GENERATOR_CRASHED', 'Generator yiqildi'), ('IGNORED', 'Hisobga olinmadi'), ('RATE_LIMITED', 'Tezlik chegarasi')], db_index=True, default='TESTING', max_length=20)),
                ('stage', models.CharField(choices=[('generate', 'Generator'), ('reference', 'Etalon yechim'), ('defend', 'Himoyachi'), ('done', 'Tugadi')], default='reference', max_length=12)),
                ('input_ref', models.CharField(blank=True, max_length=500)),
                ('output_ref', models.CharField(blank=True, max_length=500)),
                ('input_size', models.PositiveIntegerField(default=0)),
                ('generator_source', models.TextField(blank=True)),
                ('defender_verdict', models.CharField(blank=True, max_length=24)),
                ('detail', models.TextField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('added_test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hack_source', to='problems.testcase')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hacks', to='contests.contest')),
                ('defender_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacks', to='judging.attempt')),
                ('generator_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='problems.language')),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacks_made', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacks', to='problems.problem')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['problem', '-created_at'], name='hack_problem_feed'), models.Index(fields=['contest', 'status'], name='hack_contest_status'), models.Index(fields=['hacker', '-created_at'], name='hack_by_user')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'TESTING')), fields=('hacker', 'defender_attempt'), name='uniq_hack_in_flight')],
            },
        ),
        migrations.CreateModel(
            name='HackLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hack_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('contest', 'problem', 'user'), name='uniq_hack_lock')],
            },
        ),
        migrations.AddConstraint(
            model_name='hackroom',
            constraint=models.UniqueConstraint(fields=('contest', 'number'), name='uniq_room_number'),
        ),
        migrations.AddConstraint(
            model_name='hackroommember',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='uniq_room_member'),
        ),
    ]
