# Generated by Django 5.2.17 on 2026-09-06 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('compile_cmd', models.JSONField(blank=True, default=list)),
                ('run_cmd', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField(help_text='Markdown + LaTeX')),
                ('statement_locale', models.CharField(default='uz', max_length=2)),
                ('difficulty', models.PositiveIntegerField(db_index=True, help_text='800–3500, qadam 100', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(3500)])),
                ('time_limit_ms', models.PositiveIntegerField(default=1000)),
                ('memory_limit_kb', models.PositiveIntegerField(default=262144)),
                ('checker_type', models.CharField(choices=[('standard', 'Standart'), ('special', 'Maxsus'), ('interactive', 'Interactive')], default='standard', max_length=16)),
                ('interactor_source', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('interactor_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.language')),
            ],
            options={
                'ordering': ['difficulty', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('scoring', models.CharField(choices=[('min', 'min'), ('sum', 'sum')], default='min', max_length=8)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('input_ref', models.CharField(max_length=500)),
                ('output_ref', models.CharField(max_length=500)),
                ('is_sample', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='problems.problem')),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='problems.subtask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='problems.topic')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.topic'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(fields=('problem', 'order'), name='uniq_subtask_order'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('problem', 'order'), name='uniq_test_order'),
        ),
    ]
