# Generated by Django 5.2.17 on 2026-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.TextField(blank=True, help_text='Markdown + LaTeX'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, help_text='Markdown + LaTeX'),
        ),
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, help_text='Markdown + LaTeX'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, help_text='Markdown + LaTeX'),
        ),
    ]
