# Generated by Django 5.2.17 on 2026-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_favourite_problemrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
