# Generated by Django 5.2.17 on 2026-09-08 12:48

from django.db import migrations, models


def seed_counter(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    """Hisoblagichni mavjud eng katta raqamdan boshlaymiz.

    Aks holda birinchi yangi masala `#0001` olib, backfill bergan raqamni
    takrorlardi.
    """
    Problem = apps.get_model("problems", "Problem")
    Sequence = apps.get_model("problems", "ProblemCodeSequence")
    top = Problem.objects.exclude(code=None).order_by("-code").values_list("code", flat=True).first()
    Sequence.objects.update_or_create(pk=1, defaults={"value": top or 0})


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_backfill_problem_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]

    operations += [migrations.RunPython(seed_counter, migrations.RunPython.noop)]
