# Generated by Django 5.2.17 on 2026-09-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_code_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
