# Generated by Django 5.2.17 on 2026-09-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='partial_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='source_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='checker_type',
            field=models.CharField(choices=[('standard', 'Standart'), ('special', 'Maxsus'), ('interactive', 'Interactive'), ('scorer', 'Skoring')], default='standard', max_length=16),
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='problems.problem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validators', to='problems.language')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validator', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('code_template', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='problems.problem')),
            ],
            options={
                'ordering': ['language__name'],
                'constraints': [models.UniqueConstraint(fields=('problem', 'language'), name='uniq_problem_language')],
            },
        ),
        migrations.CreateModel(
            name='SimilarProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('source', models.CharField(default='import', max_length=32)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='problems.problem')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='problems.problem')),
            ],
            options={
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('problem', 'similar'), name='uniq_similar_problem')],
            },
        ),
    ]
