# Generated by Django 5.2.17 on 2026-09-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_editorial_price_editorialunlock_problemvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('statement', 'Matnda xato'), ('tests', "Testlar noto'g'ri"), ('translation', 'Tarjima xato'), ('duplicate', 'Takroriy masala'), ('other', 'Boshqa')], max_length=16)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user', 'problem'), name='uniq_open_problem_report')],
            },
        ),
    ]
