# Generated by Django 5.2.17 on 2026-09-09 11:47

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Mavjud sarlavhalar uchun qidiruv shaklini to'ldiradi."""
    from problems.models import normalize_search

    Problem = apps.get_model("problems", "Problem")
    rows = []
    for problem in Problem.objects.only("pk", "title").iterator():
        problem.title_search = normalize_search(problem.title)
        rows.append(problem)
    Problem.objects.bulk_update(rows, ["title_search"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_problemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title_search',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
