# Generated by Django 5.2.17 on 2026-09-09 11:56

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Mavjud mavzular uchun qidiruv shaklini to'ldiradi."""
    from problems.models import normalize_search

    Topic = apps.get_model("problems", "Topic")
    rows = []
    for topic in Topic.objects.only("pk", "name_uz").iterator():
        topic.name_search = normalize_search(topic.name_uz)
        rows.append(topic)
    Topic.objects.bulk_update(rows, ["name_search"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_problem_title_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name_search',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
