# Generated by Django 5.2.17 on 2026-09-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_topic_name_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checker_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.language'),
        ),
        migrations.AddField(
            model_name='problem',
            name='checker_source',
            field=models.TextField(blank=True),
        ),
    ]
