# Generated by Django 5.2.17 on 2026-09-10 05:49

from django.db import migrations, models

#: JVM bo'sh dasturda ham 18 ta oqim ochadi, `javac` esa 27 taga chiqadi
#: (o'lchandi). Standart 1 bilan har bir Java yuborishi «unable to create
#: native thread» berardi, ya'ni mavjud o'rnatmalarda ham to'g'rilanishi
#: kerak — yangi maydonning standarti buni o'zi hal qilmaydi.
JVM_PROCESS_LIMIT = 32


def set_jvm_limit(apps, schema_editor):
    apps.get_model("problems", "Language").objects.filter(code__startswith="java").update(
        process_limit=JVM_PROCESS_LIMIT
    )


def unset(apps, schema_editor):
    apps.get_model("problems", "Language").objects.filter(code__startswith="java").update(
        process_limit=1
    )


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0013_problem_checker_language_problem_checker_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="process_limit",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(set_jvm_limit, unset),
    ]
