# Generated by Django 5.2.17 on 2026-09-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_language_process_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='origin',
            field=models.CharField(choices=[('author', 'Muallif'), ('hack', 'Hack')], default='author', max_length=8),
        ),
        migrations.CreateModel(
            name='ReferenceSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_solutions', to='problems.language')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_solution', to='problems.problem')),
            ],
        ),
    ]
