# Generated by Django 5.2.17 on 2026-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0025_problem_io_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='group',
            field=models.CharField(choices=[('sample', 'Namuna'), ('minimal', 'Minimal'), ('boundary', 'Chegara'), ('special', 'Alohida holat'), ('random', 'Tasodifiy'), ('adversarial', 'Qarshi'), ('maximum', 'Maksimal'), ('stress', 'Stress'), ('unclassified', 'Tasniflanmagan')], default='unclassified', help_text='Semantik toifa; nashr talabi `problems/testgroups.py` da.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem', 'group'], name='test_problem_group_idx'),
        ),
    ]
