# Generated by Django 5.2.17 on 2026-09-30 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_backfill_test_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('version', models.CharField(max_length=32)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('architecture', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'judge environments',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ProblemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('validating', 'Tekshirilmoqda'), ('ready', 'Tayyor'), ('frozen', 'Muzlatilgan'), ('published', 'Nashr qilingan'), ('deprecated', 'Eskirgan')], default='draft', max_length=12)),
                ('package', models.JSONField(default=dict)),
                ('package_hash', models.CharField(blank=True, max_length=64)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('gate_report', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('judge_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.judgeenvironment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='problems.problem')),
            ],
            options={
                'ordering': ['problem', '-version'],
            },
        ),
        migrations.CreateModel(
            name='LimitCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurements', models.JSONField(default=dict)),
                ('safety_factor', models.FloatField(default=2.0)),
                ('time_limit_ms', models.PositiveIntegerField()),
                ('memory_limit_kb', models.PositiveIntegerField()),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.language')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='problems.problemrevision')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.problemrevision'),
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('reference', 'Etalon'), ('brute_force', 'Brute-force'), ('alternative', 'Alternativa'), ('slow', 'Sekin (TLE kutiladi)'), ('wrong', 'Xato (WA kutiladi)')], max_length=16)),
                ('source', models.TextField(blank=True)),
                ('expected_verdict', models.CharField(blank=True, max_length=8)),
                ('target_group', models.CharField(blank=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem')),
            ],
            options={
                'ordering': ['role', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='problemrevision',
            constraint=models.UniqueConstraint(fields=('problem', 'version'), name='uniq_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='problemsolution',
            constraint=models.UniqueConstraint(fields=('problem', 'role'), name='uniq_solution_role'),
        ),
    ]
