# Generated by Django 5.2.17 on 2026-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0028_package_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checker_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validator',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
