# Generated by Django 5.2.17 on 2026-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeenvironment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
