# Generated by Django 5.2.17 on 2026-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_search_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='task_kind',
            field=models.CharField(choices=[('program', 'Whole program'), ('function', 'Function')], default='program', help_text='function: the submission is inserted into the per-language harness.', max_length=16),
        ),
        migrations.AddField(
            model_name='problemlanguage',
            name='harness',
            field=models.TextField(blank=True),
        ),
    ]
