# Generated by Django 5.2.17 on 2026-10-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0032_task_kind_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task_kind',
            field=models.CharField(choices=[('program', 'Whole program'), ('function', 'Function'), ('answer', 'Answer files')], default='program', help_text='function: the submission is inserted into the per-language harness.', max_length=16),
        ),
    ]
