# Generated by Django 5.2.17 on 2026-10-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_task_kind_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='manager_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.language'),
        ),
        migrations.AddField(
            model_name='problem',
            name='manager_source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='task_kind',
            field=models.CharField(choices=[('program', 'Whole program'), ('function', 'Function'), ('answer', 'Answer files'), ('two_pass', 'Two passes')], default='program', help_text='function: the submission is inserted into the per-language harness.', max_length=16),
        ),
    ]
