# Generated by Django 5.2.17 on 2026-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0034_task_kind_two_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task_kind',
            field=models.CharField(choices=[('program', 'Whole program'), ('function', 'Function'), ('answer', 'Answer files'), ('two_pass', 'Two passes'), ('sql', 'SQL query')], default='program', help_text='function: the submission is inserted into the per-language harness.', max_length=16),
        ),
    ]
