#!/usr/bin/env python3
"""Keep `apps/web/src/app/fonts.ts` and the vendored fonts in step.

`localFont` is a compile-time transform: its `src` entries cannot be
computed by a helper, they have to be written out as literals. So
`fonts.ts` lists all 110 faces by hand, and a hand edit can point at the
wrong file, the wrong weight, or a file that does not exist — and the
build would still succeed, silently serving the wrong glyphs.

So the literals are asserted here against the data that was actually
downloaded, rather than assumed. Run without arguments it is a check.

    python3 tools/check_fonts.py

`fonts.ts` lives in `src/app/`, the fonts in `src/fonts/`, so the
literals are written `../fonts/<directory>/<file>.woff2`.

Exit codes follow the repository convention:
    0  match
    1  drift — the tree and `fonts.ts` disagree
    2  could not measure (missing manifest / CSS)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import _console

_console.force_utf8()

ROOT = Path(__file__).resolve().parent.parent
FONTS_TS = ROOT / "apps" / "web" / "src" / "app" / "fonts.ts"
FONT_ROOT = ROOT / "apps" / "web" / "src" / "fonts"
MANIFEST = FONT_ROOT / "manifest.json"

FACE = re.compile(r"/\* ([a-z-]+) \*/\s*(@font-face\s*\{[^}]*\})")
# One `const NAME = localFont({ ... });` per family.
CALL = re.compile(r"const (\w+) = localFont\(\{(.*?)\n\}\);", re.S)
# `{ path: "../fonts/inter/inter-0.woff2", weight: "400", style: "normal" },`
FACE_ENTRY = re.compile(
    r'\{\s*path:\s*"\.\./fonts/([^"]+)"\s*,\s*weight:\s*"([^"]+)"\s*,\s*style:\s*"([^"]+)"\s*\}'
)


def parse_fonts_ts() -> dict[str, dict]:
    """Pull the `src` entries out of every `localFont({...})` call.

    `localFont` is a compile-time transform, so the declarations cannot be
    generated by a helper — they are written out as literals. That is
    exactly why this parser exists: the literals are compared against the
    manifest so a hand edit cannot silently point at the wrong file.
    """
    if not FONTS_TS.is_file():
        raise SystemExit(2)

    source = FONTS_TS.read_text(encoding="utf8")

    functions: dict[str, dict] = {}
    for const, body in CALL.findall(source):
        variable = re.search(r'variable:\s*"([\w-]+)"', body)
        faces = FACE_ENTRY.findall(body)
        if not faces:
            continue

        # The directory is the leading path segment of the first entry —
        # the const name is not a reliable key (`jakarta` belongs to
        # `plus-jakarta-sans`, `plexMono` to `ibm-plex-mono`).
        directory = faces[0][0].split("/", 1)[0]
        functions[directory] = {
            "const": const,
            "variable": variable.group(1) if variable else "",
            "faces": [list(face) for face in faces],
        }
    return functions


def parse_css(directory: Path) -> list[dict]:
    """Actual `@font-face` entries in the downloaded stylesheet, in order."""
    css_path = directory / "fonts.css"
    if not css_path.is_file():
        raise SystemExit(2)
    css = css_path.read_text(encoding="utf8")
    entries = []
    for subset, block in FACE.findall(css):
        entries.append(
            {
                "subset": subset,
                "file": re.search(r"url\(\./([^)]+)\)", block).group(1),
                "weight": re.search(r"font-weight:\s*(\S+?);", block).group(1),
                "style": re.search(r"font-style:\s*(\S+?);", block).group(1),
                "range": re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip(),
            }
        )
    return entries


def main() -> int:
    if not MANIFEST.is_file():
        print("✕ apps/web/src/fonts/manifest.json topilmadi — `python3 tools/vendor_fonts.py`")
        return 2

    manifest = json.loads(MANIFEST.read_text(encoding="utf8"))
    declared = parse_fonts_ts()
    by_prefix = {entry["directory"]: entry for entry in manifest["families"]}

    problems: list[str] = []

    # 1. Every vendored family must be declared in `fonts.ts`, and vice versa.
    missing = set(by_prefix) - set(declared)
    extra = set(declared) - set(by_prefix)
    for name in sorted(missing):
        problems.append(f"fonts.ts: `{name}` oilasi e'lon qilinmagan")
    for name in sorted(extra):
        problems.append(f"fonts.ts: `{name}` repoda yo'q")

    # 2. `fonts.ts` must list exactly the faces Google served, in order,
    #    pointing at the files that are actually on disk.
    checked = 0
    for prefix in sorted(set(by_prefix) & set(declared)):
        entries = parse_css(FONT_ROOT / prefix)
        declared_faces = declared[prefix]["faces"]

        if len(entries) != len(declared_faces):
            problems.append(
                f"{prefix}: CSS'da {len(entries)} yozuv, fonts.ts'da {len(declared_faces)}"
            )
            continue

        for index, (entry, face) in enumerate(zip(entries, declared_faces)):
            file, weight, style = face
            expected_path = f"{prefix}/{entry['file']}"
            if file != expected_path:
                problems.append(f"{prefix}[{index}]: yo'l `{file}`, kutilgan `{expected_path}`")
            if weight != entry["weight"]:
                problems.append(f"{prefix}[{index}]: weight `{weight}`, kutilgan `{entry['weight']}`")
            if style != entry["style"]:
                problems.append(f"{prefix}[{index}]: style `{style}`, kutilgan `{entry['style']}`")
            if not (FONT_ROOT / file).is_file():
                problems.append(f"{prefix}[{index}]: `{file}` diskda yo'q")
            checked += 1
    if problems:
        print(f"✕ Shrift ta'riflari mos emas — {len(problems)} muammo:")
        for item in problems[:25]:
            print(f"    {item}")
        if len(problems) > 25:
            print(f"    ... yana {len(problems) - 25} ta")
        return 1

    print(f"✓ Shrift ta'riflari joyida: {len(declared)} oila, {checked} yozuv")
    return 0


if __name__ == "__main__":
    sys.exit(main())
