#!/usr/bin/env python3
"""Notification wording: copy it from the web dictionaries to the API.

A coded notification (`duel_accepted`, `contest_result`, …) is written
once, in `apps/web/src/i18n/locales/*.ts` under `notif.msg.<code>.title`
and `.body`. The site reads those directly. The API needs the same
sentences for the message it hands to Telegram and for the fallback text
stored on the row — and it cannot read TypeScript.

This tool writes them into `apps/api/notifications/message_catalog.py`.

    python tools/export_notification_messages.py            # rewrite the module
    python tools/export_notification_messages.py --check    # exit 1 if it is stale

`--check` runs in CI: a sentence changed on the site and not exported
would leave Telegram saying something else, and nothing would show it.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

import _console

_console.force_utf8()

ROOT = pathlib.Path(__file__).resolve().parents[1]
LOCALES = ROOT / "apps/web/src/i18n/locales"
TARGET = ROOT / "apps/api/notifications/message_catalog.py"

PREFIX = "notif.msg."
PAIR = re.compile(r'^\s*(?:"([^"]+)"|([A-Za-z_$][\w$]*)):\s*"((?:[^"\\]|\\.)*)",\s*$', re.M)

HEADER = '''"""Generated by `tools/export_notification_messages.py` — do not edit.

The sentences live in `apps/web/src/i18n/locales/*.ts` (`notif.msg.*`).
"""

# ruff: noqa: E501

CATALOG: dict[str, dict[str, dict[str, str]]] = {
'''


def load(path: pathlib.Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    return {a or b: json.loads(f'"{c}"') for a, b, c in PAIR.findall(text)}


def collect() -> dict[str, dict[str, dict[str, str]]]:
    out: dict[str, dict[str, dict[str, str]]] = {}
    for path in sorted(LOCALES.glob("*.ts")):
        codes: dict[str, dict[str, str]] = {}
        for key, value in load(path).items():
            if not key.startswith(PREFIX):
                continue
            code, _, part = key[len(PREFIX) :].rpartition(".")
            if part in ("title", "body") and code:
                codes.setdefault(code, {})[part] = value
        if codes:
            out[path.stem] = dict(sorted(codes.items()))
    return out


def literal(text: str) -> str:
    """A Python string literal the formatter leaves alone (double quotes)."""
    return json.dumps(text, ensure_ascii=False)


def render(table: dict[str, dict[str, dict[str, str]]]) -> str:
    lines = [HEADER.rstrip("\n")]
    for locale, codes in table.items():
        lines.append(f"    {literal(locale)}: {{")
        for code, parts in codes.items():
            lines.append(f"        {literal(code)}: {{")
            for part in ("title", "body"):
                if part in parts:
                    lines.append(f"            {literal(part)}: {literal(parts[part])},")
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the module is stale")
    args = parser.parse_args()

    table = collect()
    if "uz" not in table:
        print(f"✗ {PREFIX}* kalitlari topilmadi — {LOCALES}")
        return 2
    source = set(table["uz"])
    problems = [
        f"{locale}: {sorted(source ^ set(codes))[:4]}"
        for locale, codes in table.items()
        if set(codes) != source
    ]
    if problems:
        print("✗ tillarda xabar kodlari bir xil emas:")
        for row in problems:
            print(f"  {row}")
        return 1
    if any('"' in text for codes in table.values() for parts in codes.values() for text in parts.values()):
        # A straight quote would make the formatter flip the literal to
        # single quotes, and the generated file would never match itself.
        print("✗ xabar matnida to'g'ri qo'shtirnoq (\") bor — «» yoki “” ishlating")
        return 1

    wanted = render(table)
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != wanted:
            print(
                f"✗ {TARGET.relative_to(ROOT).as_posix()} eskirgan — "
                "`python tools/export_notification_messages.py` ni yurgizing"
            )
            return 1
        print(f"✓ Bildirishnoma matnlari mos: {len(table)} til × {len(source)} kod")
        return 0
    TARGET.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"✓ yozildi: {len(table)} til × {len(source)} kod → {TARGET.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
