# Generated by Django 5.2.17 on 2026-09-06 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QvantQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('achievement', 'Yutuq')], max_length=12)),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('reward', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('streak_freeze', 'Streak freeze'), ('avatar_frame', 'Avatar ramka'), ('profile_cover', 'Profil cover'), ('username_badge', 'Username badge')], max_length=20)),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('asset_ref', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_consumable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QvantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QvantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Musbat = topildi, manfiy = sarflandi')),
                ('reason', models.CharField(choices=[('quest', 'Quest'), ('streak', "Streak yutug'i"), ('contest', 'Musobaqa'), ('purchase', 'Xarid'), ('refund', 'Qaytarish'), ('admin', 'Admin')], max_length=16)),
                ('ref_type', models.CharField(blank=True, max_length=24)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qvant_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='qvant_tx_feed'), models.Index(fields=['user', 'reason', 'created_at'], name='qvant_tx_cap')],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='qvant.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'item'], name='inventory_lookup')],
            },
        ),
        migrations.CreateModel(
            name='UserQuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=24)),
                ('awarded', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='qvant.qvantquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='quest_activity_window')],
                'constraints': [models.UniqueConstraint(fields=('user', 'quest', 'period_key'), name='uniq_quest_period')],
            },
        ),
    ]
