# Generated by Django 5.2.17 on 2026-09-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qvant', '0003_alter_qvanttransaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qvanttransaction',
            name='reason',
            field=models.CharField(choices=[('quest', 'Quest'), ('streak', "Streak yutug'i"), ('contest', 'Musobaqa'), ('purchase', 'Xarid'), ('refund', 'Qaytarish'), ('admin', 'Admin'), ('quiz', 'Test'), ('arena', 'Arena'), ('duel', 'Duel'), ('achievement', 'Yutuq'), ('hack', 'Hack')], max_length=16),
        ),
    ]
