# Generated by Django 5.2.17 on 2026-09-06 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('finished', 'Tugadi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='open', max_length=12)),
                ('problem_count', models.PositiveIntegerField(default=4)),
                ('difficulty', models.PositiveIntegerField(default=1200)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('challenger_solved', models.PositiveIntegerField(default=0)),
                ('opponent_solved', models.PositiveIntegerField(default=0)),
                ('is_draw', models.BooleanField(default=False)),
                ('ratings_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_challenged', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_accepted', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuelProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='duels.duel')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='duel',
            name='problems',
            field=models.ManyToManyField(through='duels.DuelProblem', to='problems.problem'),
        ),
        migrations.AddConstraint(
            model_name='duelproblem',
            constraint=models.UniqueConstraint(fields=('duel', 'order'), name='uniq_duel_problem_order'),
        ),
        migrations.AddConstraint(
            model_name='duelproblem',
            constraint=models.UniqueConstraint(fields=('duel', 'problem'), name='uniq_duel_problem'),
        ),
    ]
