"""Generated by `tools/export_notification_messages.py` — do not edit.

The sentences live in `apps/web/src/i18n/locales/*.ts` (`notif.msg.*`).
"""

# ruff: noqa: E501

CATALOG: dict[str, dict[str, dict[str, str]]] = {
    "en": {
        "contest_result": {
            "title": "{contest}: place {rank}, rating {delta}",
            "body": "Contests rating: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} accepted your challenge",
            "body": "“{duel}” starts at {start_at}.",
        },
        "duel_cancelled": {
            "title": "The duel was cancelled by an administrator",
            "body": "“{duel}” will not take place.",
        },
        "duel_draw": {
            "title": "Duel over: a draw",
            "body": "“{duel}” — score: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Duel over: you lost",
            "body": "“{duel}” — score: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Duel over: you won",
            "body": "“{duel}” — score: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Generator crashed — {problem}",
        },
        "hack_failed": {
            "title": "Hack failed — {problem}",
        },
        "hack_ignored": {
            "title": "Hack was ignored — {problem}",
        },
        "hack_invalid": {
            "title": "Hack test is invalid — {problem}",
        },
        "hack_received": {
            "title": "Your solution was hacked — {problem}",
            "body": "Verdict on the new test: {verdict}",
        },
        "hack_succeeded": {
            "title": "Hack succeeded — {problem}",
        },
        "hackathon_scored": {
            "title": "Hackathon score: {score}/100",
        },
        "problem_rerated": {
            "title": "Your Skills rating changed by {delta}",
            "body": "A problem you solved was re-rated. Skills: {before} → {after}. This was not your action — the difficulty was updated from statistics.",
        },
        "streak": {
            "title": "{days}-day streak!",
            "body": "Qvant was added for the streak milestone.",
        },
    },
    "es": {
        "contest_result": {
            "title": "{contest}: puesto {rank}, rating {delta}",
            "body": "Rating de Contests: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} aceptó tu reto",
            "body": "«{duel}» empieza el {start_at}.",
        },
        "duel_cancelled": {
            "title": "Un administrador canceló el duelo",
            "body": "«{duel}» no se celebrará.",
        },
        "duel_draw": {
            "title": "Duelo terminado: empate",
            "body": "«{duel}» — marcador: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Duelo terminado: derrota",
            "body": "«{duel}» — marcador: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Duelo terminado: victoria",
            "body": "«{duel}» — marcador: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "El generador falló — {problem}",
        },
        "hack_failed": {
            "title": "Hack fallido — {problem}",
        },
        "hack_ignored": {
            "title": "El hack no se contó — {problem}",
        },
        "hack_invalid": {
            "title": "La prueba del hack no es válida — {problem}",
        },
        "hack_received": {
            "title": "Tu solución fue hackeada — {problem}",
            "body": "Veredicto en la nueva prueba: {verdict}",
        },
        "hack_succeeded": {
            "title": "Hack logrado — {problem}",
        },
        "hackathon_scored": {
            "title": "Puntuación del hackatón: {score}/100",
        },
        "problem_rerated": {
            "title": "Tu rating de Skills cambió en {delta}",
            "body": "Un problema que resolviste fue reevaluado. Skills: {before} → {after}. No fue una acción tuya: la dificultad se actualizó según las estadísticas.",
        },
        "streak": {
            "title": "¡Racha de {days} días!",
            "body": "Se añadió Qvant por el logro de racha.",
        },
    },
    "kaa": {
        "contest_result": {
            "title": "{contest}: {rank}-orın, reyting {delta}",
            "body": "Contests reytingi: {before} → {after}.",
        },
        "duel_accepted": {
            "title": "{user} shaqırıǵıńızdı qabıl etti",
            "body": "«{duel}» {start_at} da baslanadı.",
        },
        "duel_cancelled": {
            "title": "Duel administrator tárepinen biykar etildi",
            "body": "«{duel}» ótkerilmeydi.",
        },
        "duel_draw": {
            "title": "Duel tamamlandı: teń",
            "body": "«{duel}» — esap: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Duel tamamlandı: jeńilis",
            "body": "«{duel}» — esap: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Duel tamamlandı: jeńis",
            "body": "«{duel}» — esap: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Generator qulap tústi — {problem}",
        },
        "hack_failed": {
            "title": "Hack tabıssız — {problem}",
        },
        "hack_ignored": {
            "title": "Hack esapqa alınbadı — {problem}",
        },
        "hack_invalid": {
            "title": "Hack testi jaramsız — {problem}",
        },
        "hack_received": {
            "title": "Sheshimińiz hack qılındı — {problem}",
            "body": "Jańa testte verdikt: {verdict}",
        },
        "hack_succeeded": {
            "title": "Hack tabıslı — {problem}",
        },
        "hackathon_scored": {
            "title": "Xakaton bahası: {score}/100",
        },
        "problem_rerated": {
            "title": "Skills reytingińiz {delta} ge ózgerdi",
            "body": "Siz sheshken másele qayta bahalandı. Skills: {before} → {after}. Bul sizdiń háreketińiz emes — másele qıyınlıǵı statistika tiykarında jańalandı.",
        },
        "streak": {
            "title": "{days} kúnlik streak!",
            "body": "Streak jetiskenligi ushın Qvant qosıldı.",
        },
    },
    "kk": {
        "contest_result": {
            "title": "{contest}: {rank}-орын, рейтинг {delta}",
            "body": "Contests рейтингі: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} шақыруыңызды қабылдады",
            "body": "«{duel}» {start_at} басталады.",
        },
        "duel_cancelled": {
            "title": "Дуэльді әкімші тоқтатты",
            "body": "«{duel}» өткізілмейді.",
        },
        "duel_draw": {
            "title": "Дуэль аяқталды: тең",
            "body": "«{duel}» — есеп: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Дуэль аяқталды: жеңіліс",
            "body": "«{duel}» — есеп: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Дуэль аяқталды: жеңіс",
            "body": "«{duel}» — есеп: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Генератор құлады — {problem}",
        },
        "hack_failed": {
            "title": "Хак сәтсіз — {problem}",
        },
        "hack_ignored": {
            "title": "Хак есепке алынбады — {problem}",
        },
        "hack_invalid": {
            "title": "Хак тесті жарамсыз — {problem}",
        },
        "hack_received": {
            "title": "Шешіміңіз бұзылды — {problem}",
            "body": "Жаңа тесттегі вердикт: {verdict}",
        },
        "hack_succeeded": {
            "title": "Хак сәтті — {problem}",
        },
        "hackathon_scored": {
            "title": "Хакатон бағасы: {score}/100",
        },
        "problem_rerated": {
            "title": "Skills рейтингіңіз {delta} өзгерді",
            "body": "Сіз шешкен есеп қайта бағаланды. Skills: {before} → {after}. Бұл сіздің әрекетіңіз емес — есеп қиындығы статистика бойынша жаңартылды.",
        },
        "streak": {
            "title": "{days} күндік серия!",
            "body": "Серия жетістігі үшін Qvant қосылды.",
        },
    },
    "ky": {
        "contest_result": {
            "title": "{contest}: {rank}-орун, рейтинг {delta}",
            "body": "Contests рейтинги: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} чакырыгыңызды кабыл алды",
            "body": "«{duel}» {start_at} башталат.",
        },
        "duel_cancelled": {
            "title": "Дуэлди администратор токтотту",
            "body": "«{duel}» өткөрүлбөйт.",
        },
        "duel_draw": {
            "title": "Дуэль бүттү: тең",
            "body": "«{duel}» — эсеп: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Дуэль бүттү: жеңилүү",
            "body": "«{duel}» — эсеп: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Дуэль бүттү: жеңиш",
            "body": "«{duel}» — эсеп: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Генератор кулады — {problem}",
        },
        "hack_failed": {
            "title": "Хак ийгиликсиз — {problem}",
        },
        "hack_ignored": {
            "title": "Хак эсепке алынган жок — {problem}",
        },
        "hack_invalid": {
            "title": "Хак тести жараксыз — {problem}",
        },
        "hack_received": {
            "title": "Чечимиңиз бузулду — {problem}",
            "body": "Жаңы тесттеги вердикт: {verdict}",
        },
        "hack_succeeded": {
            "title": "Хак ийгиликтүү — {problem}",
        },
        "hackathon_scored": {
            "title": "Хакатон баасы: {score}/100",
        },
        "problem_rerated": {
            "title": "Skills рейтингиңиз {delta} өзгөрдү",
            "body": "Сиз чечкен маселе кайра бааланды. Skills: {before} → {after}. Бул сиздин аракетиңиз эмес — маселенин татаалдыгы статистика боюнча жаңыланды.",
        },
        "streak": {
            "title": "{days} күндүк серия!",
            "body": "Серия жетишкендиги үчүн Qvant кошулду.",
        },
    },
    "ru": {
        "contest_result": {
            "title": "{contest}: {rank}-е место, рейтинг {delta}",
            "body": "Рейтинг Contests: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} принял ваш вызов",
            "body": "«{duel}» начнётся {start_at}.",
        },
        "duel_cancelled": {
            "title": "Дуэль отменена администратором",
            "body": "«{duel}» не состоится.",
        },
        "duel_draw": {
            "title": "Дуэль окончена: ничья",
            "body": "«{duel}» — счёт: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Дуэль окончена: поражение",
            "body": "«{duel}» — счёт: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Дуэль окончена: победа",
            "body": "«{duel}» — счёт: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Генератор упал — {problem}",
        },
        "hack_failed": {
            "title": "Взлом не удался — {problem}",
        },
        "hack_ignored": {
            "title": "Взлом не засчитан — {problem}",
        },
        "hack_invalid": {
            "title": "Тест для взлома некорректен — {problem}",
        },
        "hack_received": {
            "title": "Ваше решение взломано — {problem}",
            "body": "Вердикт на новом тесте: {verdict}",
        },
        "hack_succeeded": {
            "title": "Взлом удался — {problem}",
        },
        "hackathon_scored": {
            "title": "Оценка хакатона: {score}/100",
        },
        "problem_rerated": {
            "title": "Ваш рейтинг Skills изменился на {delta}",
            "body": "Решённая вами задача переоценена. Skills: {before} → {after}. Это не ваше действие — сложность задачи обновлена по статистике.",
        },
        "streak": {
            "title": "Серия {days} дней!",
            "body": "За достижение серии начислен Qvant.",
        },
    },
    "tg": {
        "contest_result": {
            "title": "{contest}: ҷойи {rank}, рейтинг {delta}",
            "body": "Рейтинги Contests: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} даъвати шуморо қабул кард",
            "body": "«{duel}» {start_at} оғоз мешавад.",
        },
        "duel_cancelled": {
            "title": "Дуэлро маъмур бекор кард",
            "body": "«{duel}» баргузор намешавад.",
        },
        "duel_draw": {
            "title": "Дуэл анҷом ёфт: мусовӣ",
            "body": "«{duel}» — ҳисоб: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Дуэл анҷом ёфт: шикаст",
            "body": "«{duel}» — ҳисоб: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Дуэл анҷом ёфт: ғалаба",
            "body": "«{duel}» — ҳисоб: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Генератор аз кор монд — {problem}",
        },
        "hack_failed": {
            "title": "Ҳак муваффақ нашуд — {problem}",
        },
        "hack_ignored": {
            "title": "Ҳак ба ҳисоб гирифта нашуд — {problem}",
        },
        "hack_invalid": {
            "title": "Тести ҳак нодуруст аст — {problem}",
        },
        "hack_received": {
            "title": "Ҳалли шумо шикаста шуд — {problem}",
            "body": "Вердикт дар тести нав: {verdict}",
        },
        "hack_succeeded": {
            "title": "Ҳак муваффақ шуд — {problem}",
        },
        "hackathon_scored": {
            "title": "Баҳои хакатон: {score}/100",
        },
        "problem_rerated": {
            "title": "Рейтинги Skills-и шумо {delta} тағйир ёфт",
            "body": "Масъалае, ки шумо ҳал кардед, аз нав баҳогузорӣ шуд. Skills: {before} → {after}. Ин амали шумо нест — душвории масъала аз рӯи омор нав шуд.",
        },
        "streak": {
            "title": "Силсилаи {days}-рӯза!",
            "body": "Барои дастоварди силсила Qvant илова шуд.",
        },
    },
    "tr": {
        "contest_result": {
            "title": "{contest}: {rank}. sıra, puan {delta}",
            "body": "Contests puanı: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} meydan okumanızı kabul etti",
            "body": "“{duel}” {start_at} tarihinde başlıyor.",
        },
        "duel_cancelled": {
            "title": "Düello yönetici tarafından iptal edildi",
            "body": "“{duel}” yapılmayacak.",
        },
        "duel_draw": {
            "title": "Düello bitti: beraberlik",
            "body": "“{duel}” — skor: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Düello bitti: mağlubiyet",
            "body": "“{duel}” — skor: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Düello bitti: galibiyet",
            "body": "“{duel}” — skor: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Üreteç çöktü — {problem}",
        },
        "hack_failed": {
            "title": "Hack başarısız — {problem}",
        },
        "hack_ignored": {
            "title": "Hack sayılmadı — {problem}",
        },
        "hack_invalid": {
            "title": "Hack testi geçersiz — {problem}",
        },
        "hack_received": {
            "title": "Çözümünüz hacklendi — {problem}",
            "body": "Yeni testteki sonuç: {verdict}",
        },
        "hack_succeeded": {
            "title": "Hack başarılı — {problem}",
        },
        "hackathon_scored": {
            "title": "Hackathon puanı: {score}/100",
        },
        "problem_rerated": {
            "title": "Skills puanınız {delta} değişti",
            "body": "Çözdüğünüz bir soru yeniden değerlendirildi. Skills: {before} → {after}. Bu sizin işleminiz değil — sorunun zorluğu istatistiklere göre güncellendi.",
        },
        "streak": {
            "title": "{days} günlük seri!",
            "body": "Seri başarısı için Qvant eklendi.",
        },
    },
    "uz": {
        "contest_result": {
            "title": "{contest}: {rank}-o'rin, reyting {delta}",
            "body": "Contests reytingi: {before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} chaqirig'ingizni qabul qildi",
            "body": "«{duel}» {start_at} da boshlanadi.",
        },
        "duel_cancelled": {
            "title": "Duel administrator tomonidan bekor qilindi",
            "body": "«{duel}» o'tkazilmaydi.",
        },
        "duel_draw": {
            "title": "Duel tugadi: durang",
            "body": "«{duel}» — hisob: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "Duel tugadi: mag'lubiyat",
            "body": "«{duel}» — hisob: {a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "Duel tugadi: g'alaba",
            "body": "«{duel}» — hisob: {a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "Generator yiqildi — {problem}",
        },
        "hack_failed": {
            "title": "Hack muvaffaqiyatsiz — {problem}",
        },
        "hack_ignored": {
            "title": "Hack hisobga olinmadi — {problem}",
        },
        "hack_invalid": {
            "title": "Hack testi yaroqsiz — {problem}",
        },
        "hack_received": {
            "title": "Yechimingiz hack qilindi — {problem}",
            "body": "Yangi testda verdikt: {verdict}",
        },
        "hack_succeeded": {
            "title": "Hack muvaffaqiyatli — {problem}",
        },
        "hackathon_scored": {
            "title": "Xakaton bahosi: {score}/100",
        },
        "problem_rerated": {
            "title": "Skills reytingingiz {delta} ga o'zgardi",
            "body": "Siz yechgan masala qayta baholandi. Skills: {before} → {after}. Bu sizning harakatingiz emas — masala qiyinligi statistika asosida yangilandi.",
        },
        "streak": {
            "title": "{days} kunlik streak!",
            "body": "Streak yutug'i uchun Qvant qo'shildi.",
        },
    },
    "zh": {
        "contest_result": {
            "title": "{contest}:第 {rank} 名,评分 {delta}",
            "body": "Contests 评分:{before} → {after}",
        },
        "duel_accepted": {
            "title": "{user} 接受了你的挑战",
            "body": "“{duel}”将于 {start_at} 开始。",
        },
        "duel_cancelled": {
            "title": "对决已被管理员取消",
            "body": "“{duel}”不会举行。",
        },
        "duel_draw": {
            "title": "对决结束:平局",
            "body": "“{duel}”— 比分:{a} {a_solved} : {b_solved} {b}",
        },
        "duel_lost": {
            "title": "对决结束:失利",
            "body": "“{duel}”— 比分:{a} {a_solved} : {b_solved} {b}",
        },
        "duel_won": {
            "title": "对决结束:获胜",
            "body": "“{duel}”— 比分:{a} {a_solved} : {b_solved} {b}",
        },
        "hack_crashed": {
            "title": "生成器崩溃 — {problem}",
        },
        "hack_failed": {
            "title": "Hack 失败 — {problem}",
        },
        "hack_ignored": {
            "title": "Hack 未计入 — {problem}",
        },
        "hack_invalid": {
            "title": "Hack 测试无效 — {problem}",
        },
        "hack_received": {
            "title": "你的解答被 Hack — {problem}",
            "body": "新测试的结果:{verdict}",
        },
        "hack_succeeded": {
            "title": "Hack 成功 — {problem}",
        },
        "hackathon_scored": {
            "title": "黑客松得分:{score}/100",
        },
        "problem_rerated": {
            "title": "你的 Skills 评分变化 {delta}",
            "body": "你解出的一道题被重新评级。Skills:{before} → {after}。这不是你的操作 — 题目难度根据统计数据更新。",
        },
        "streak": {
            "title": "连续 {days} 天!",
            "body": "已为连续打卡成就发放 Qvant。",
        },
    },
}
