/** O'zbekiston viloyatlari — `profiles/catalog.py` dagi `UZ_REGIONS` bilan
 *  bir xil tartib va kod. Viloyat bo'yicha reyting shu kodlarga tayanadi,
 *  shuning uchun O'zbekistonda viloyat erkin matn emas, ro'yxatdan. */

import type { Locale } from "@/i18n/messages";

const REGIONS: [code: string, uz: string, ru: string, en: string][] = [
  ["toshkent-shahri", "Toshkent shahri", "г. Ташкент", "Tashkent City"],
  ["toshkent", "Toshkent viloyati", "Ташкентская область", "Tashkent Region"],
  ["andijon", "Andijon viloyati", "Андижанская область", "Andijan Region"],
  ["fargona", "Farg'ona viloyati", "Ферганская область", "Fergana Region"],
  ["namangan", "Namangan viloyati", "Наманганская область", "Namangan Region"],
  ["sirdaryo", "Sirdaryo viloyati", "Сырдарьинская область", "Syrdarya Region"],
  ["jizzax", "Jizzax viloyati", "Джизакская область", "Jizzakh Region"],
  ["samarqand", "Samarqand viloyati", "Самаркандская область", "Samarkand Region"],
  ["qashqadaryo", "Qashqadaryo viloyati", "Кашкадарьинская область", "Kashkadarya Region"],
  ["surxondaryo", "Surxondaryo viloyati", "Сурхандарьинская область", "Surkhandarya Region"],
  ["buxoro", "Buxoro viloyati", "Бухарская область", "Bukhara Region"],
  ["navoiy", "Navoiy viloyati", "Навоийская область", "Navoi Region"],
  ["xorazm", "Xorazm viloyati", "Хорезмская область", "Khorezm Region"],
  [
    "qoraqalpogiston",
    "Qoraqalpog'iston Respublikasi",
    "Республика Каракалпакстан",
    "Republic of Karakalpakstan",
  ],
];

/** Kirill yozuvli tillar ruscha nomni, lotin yozuvlilar o'zbekchasini oladi. */
const CYRILLIC: Locale[] = ["ru", "kk", "ky", "tg"];
const LATIN_UZ: Locale[] = ["uz", "kaa", "tr"];

export function regionName(code: string, locale: Locale): string {
  const row = REGIONS.find((r) => r[0] === code);
  if (!row) return code;
  return CYRILLIC.includes(locale)
    ? row[2]
    : LATIN_UZ.includes(locale)
      ? row[1]
      : row[3];
}

export const REGION_CODES = REGIONS.map((r) => r[0]);

/** Tuman va viloyatga bo'ysunuvchi shaharlar — `profiles/catalog.py` dagi
 *  `UZ_DISTRICTS` bilan bir xil kodlar. Lotin tillarida o'zbekcha, kirill
 *  tillarida ruscha nom (viloyatlar bilan bir xil qoida). */
const DISTRICTS: [code: string, region: string, kind: "t" | "sh", uz: string, ru: string][] = [
  ["bektemir", "toshkent-shahri", "t", "Bektemir", "Бектемир"],
  ["chilonzor", "toshkent-shahri", "t", "Chilonzor", "Чиланзар"],
  ["mirobod", "toshkent-shahri", "t", "Mirobod", "Мирабад"],
  ["mirzo-ulugbek", "toshkent-shahri", "t", "Mirzo Ulug'bek", "Мирзо-Улугбек"],
  ["olmazor", "toshkent-shahri", "t", "Olmazor", "Алмазар"],
  ["sergeli", "toshkent-shahri", "t", "Sergeli", "Сергели"],
  ["shayxontohur", "toshkent-shahri", "t", "Shayxontohur", "Шайхантахур"],
  ["uchtepa", "toshkent-shahri", "t", "Uchtepa", "Учтепа"],
  ["yakkasaroy", "toshkent-shahri", "t", "Yakkasaroy", "Яккасарай"],
  ["yangihayot", "toshkent-shahri", "t", "Yangihayot", "Янгихаёт"],
  ["yashnobod", "toshkent-shahri", "t", "Yashnobod", "Яшнабад"],
  ["yunusobod", "toshkent-shahri", "t", "Yunusobod", "Юнусабад"],
  ["bekobod", "toshkent", "t", "Bekobod", "Бекабад"],
  ["boka", "toshkent", "t", "Bo'ka", "Бука"],
  ["bostonliq", "toshkent", "t", "Bo'stonliq", "Бостанлык"],
  ["chinoz", "toshkent", "t", "Chinoz", "Чиназ"],
  ["ohangaron", "toshkent", "t", "Ohangaron", "Ахангаран"],
  ["oqqorgon", "toshkent", "t", "Oqqo'rg'on", "Аккурган"],
  ["orta-chirchiq", "toshkent", "t", "O'rta Chirchiq", "Уртачирчик"],
  ["parkent", "toshkent", "t", "Parkent", "Паркент"],
  ["piskent", "toshkent", "t", "Piskent", "Пскент"],
  ["qibray", "toshkent", "t", "Qibray", "Кибрай"],
  ["quyi-chirchiq", "toshkent", "t", "Quyi Chirchiq", "Куйичирчик"],
  ["toshkent-tumani", "toshkent", "t", "Toshkent tumani", "Ташкентский район"],
  ["yangiyol", "toshkent", "t", "Yangiyo'l", "Янгиюль"],
  ["yuqori-chirchiq", "toshkent", "t", "Yuqori Chirchiq", "Юкоричирчик"],
  ["zangiota", "toshkent", "t", "Zangiota", "Зангиата"],
  ["angren-sh", "toshkent", "sh", "Angren", "Ангрен"],
  ["bekobod-sh", "toshkent", "sh", "Bekobod", "Бекабад"],
  ["chirchiq-sh", "toshkent", "sh", "Chirchiq", "Чирчик"],
  ["nurafshon-sh", "toshkent", "sh", "Nurafshon", "Нурафшан"],
  ["ohangaron-sh", "toshkent", "sh", "Ohangaron", "Ахангаран"],
  ["olmaliq-sh", "toshkent", "sh", "Olmaliq", "Алмалык"],
  ["yangiyol-sh", "toshkent", "sh", "Yangiyo'l", "Янгиюль"],
  ["andijon", "andijon", "t", "Andijon", "Андижан"],
  ["asaka", "andijon", "t", "Asaka", "Асака"],
  ["baliqchi", "andijon", "t", "Baliqchi", "Балыкчи"],
  ["boston", "andijon", "t", "Bo'ston", "Бустон"],
  ["buloqboshi", "andijon", "t", "Buloqboshi", "Булакбаши"],
  ["izboskan", "andijon", "t", "Izboskan", "Избаскан"],
  ["jalaquduq", "andijon", "t", "Jalaquduq", "Джалакудук"],
  ["marhamat", "andijon", "t", "Marhamat", "Мархамат"],
  ["oltinkol", "andijon", "t", "Oltinko'l", "Алтынкуль"],
  ["paxtaobod", "andijon", "t", "Paxtaobod", "Пахтаабад"],
  ["qorgontepa", "andijon", "t", "Qo'rg'ontepa", "Кургантепа"],
  ["shahrixon", "andijon", "t", "Shahrixon", "Шахрихан"],
  ["ulugnor", "andijon", "t", "Ulug'nor", "Улугнор"],
  ["xojaobod", "andijon", "t", "Xo'jaobod", "Ходжаабад"],
  ["andijon-sh", "andijon", "sh", "Andijon", "Андижан"],
  ["xonobod-sh", "andijon", "sh", "Xonobod", "Ханабад"],
  ["bagdod", "fargona", "t", "Bag'dod", "Багдад"],
  ["beshariq", "fargona", "t", "Beshariq", "Бешарык"],
  ["buvayda", "fargona", "t", "Buvayda", "Бувайда"],
  ["dangara", "fargona", "t", "Dang'ara", "Дангара"],
  ["fargona", "fargona", "t", "Farg'ona", "Фергана"],
  ["furqat", "fargona", "t", "Furqat", "Фуркат"],
  ["oltiariq", "fargona", "t", "Oltiariq", "Алтыарык"],
  ["ozbekiston", "fargona", "t", "O'zbekiston", "Узбекистан"],
  ["qoshtepa", "fargona", "t", "Qo'shtepa", "Куштепа"],
  ["quva", "fargona", "t", "Quva", "Кува"],
  ["rishton", "fargona", "t", "Rishton", "Риштан"],
  ["sox", "fargona", "t", "So'x", "Сох"],
  ["toshloq", "fargona", "t", "Toshloq", "Ташлак"],
  ["uchkoprik", "fargona", "t", "Uchko'prik", "Учкуприк"],
  ["yozyovon", "fargona", "t", "Yozyovon", "Язъяван"],
  ["fargona-sh", "fargona", "sh", "Farg'ona", "Фергана"],
  ["margilon-sh", "fargona", "sh", "Marg'ilon", "Маргилан"],
  ["qoqon-sh", "fargona", "sh", "Qo'qon", "Коканд"],
  ["quvasoy-sh", "fargona", "sh", "Quvasoy", "Кувасай"],
  ["chortoq", "namangan", "t", "Chortoq", "Чартак"],
  ["chust", "namangan", "t", "Chust", "Чуст"],
  ["kosonsoy", "namangan", "t", "Kosonsoy", "Касансай"],
  ["mingbuloq", "namangan", "t", "Mingbuloq", "Мингбулак"],
  ["namangan", "namangan", "t", "Namangan", "Наманган"],
  ["norin", "namangan", "t", "Norin", "Нарын"],
  ["pop", "namangan", "t", "Pop", "Пап"],
  ["toraqorgon", "namangan", "t", "To'raqo'rg'on", "Туракурган"],
  ["uchqorgon", "namangan", "t", "Uchqo'rg'on", "Учкурган"],
  ["uychi", "namangan", "t", "Uychi", "Уйчи"],
  ["yangiqorgon", "namangan", "t", "Yangiqo'rg'on", "Янгикурган"],
  ["namangan-sh", "namangan", "sh", "Namangan", "Наманган"],
  ["boyovut", "sirdaryo", "t", "Boyovut", "Баяут"],
  ["guliston", "sirdaryo", "t", "Guliston", "Гулистан"],
  ["mirzaobod", "sirdaryo", "t", "Mirzaobod", "Мирзаабад"],
  ["oqoltin", "sirdaryo", "t", "Oqoltin", "Акалтын"],
  ["sardoba", "sirdaryo", "t", "Sardoba", "Сардоба"],
  ["sayxunobod", "sirdaryo", "t", "Sayxunobod", "Сайхунабад"],
  ["sirdaryo", "sirdaryo", "t", "Sirdaryo", "Сырдарья"],
  ["xovos", "sirdaryo", "t", "Xovos", "Хаваст"],
  ["guliston-sh", "sirdaryo", "sh", "Guliston", "Гулистан"],
  ["shirin-sh", "sirdaryo", "sh", "Shirin", "Ширин"],
  ["yangiyer-sh", "sirdaryo", "sh", "Yangiyer", "Янгиер"],
  ["arnasoy", "jizzax", "t", "Arnasoy", "Арнасай"],
  ["baxmal", "jizzax", "t", "Baxmal", "Бахмал"],
  ["dostlik", "jizzax", "t", "Do'stlik", "Дустлик"],
  ["forish", "jizzax", "t", "Forish", "Фариш"],
  ["gallaorol", "jizzax", "t", "G'allaorol", "Галляарал"],
  ["mirzachol", "jizzax", "t", "Mirzacho'l", "Мирзачуль"],
  ["paxtakor", "jizzax", "t", "Paxtakor", "Пахтакор"],
  ["sharof-rashidov", "jizzax", "t", "Sharof Rashidov", "Шараф Рашидов"],
  ["yangiobod", "jizzax", "t", "Yangiobod", "Янгиабад"],
  ["zafarobod", "jizzax", "t", "Zafarobod", "Зафарабад"],
  ["zarbdor", "jizzax", "t", "Zarbdor", "Зарбдар"],
  ["zomin", "jizzax", "t", "Zomin", "Заамин"],
  ["jizzax-sh", "jizzax", "sh", "Jizzax", "Джизак"],
  ["bulungur", "samarqand", "t", "Bulung'ur", "Булунгур"],
  ["ishtixon", "samarqand", "t", "Ishtixon", "Иштыхан"],
  ["jomboy", "samarqand", "t", "Jomboy", "Джамбай"],
  ["kattaqorgon", "samarqand", "t", "Kattaqo'rg'on", "Каттакурган"],
  ["narpay", "samarqand", "t", "Narpay", "Нарпай"],
  ["nurobod", "samarqand", "t", "Nurobod", "Нурабад"],
  ["oqdaryo", "samarqand", "t", "Oqdaryo", "Акдарья"],
  ["pastdargom", "samarqand", "t", "Pastdarg'om", "Пастдаргом"],
  ["paxtachi", "samarqand", "t", "Paxtachi", "Пахтачи"],
  ["payariq", "samarqand", "t", "Payariq", "Паярык"],
  ["qoshrabot", "samarqand", "t", "Qo'shrabot", "Кошрабад"],
  ["samarqand", "samarqand", "t", "Samarqand", "Самарканд"],
  ["tayloq", "samarqand", "t", "Tayloq", "Тайлак"],
  ["urgut", "samarqand", "t", "Urgut", "Ургут"],
  ["kattaqorgon-sh", "samarqand", "sh", "Kattaqo'rg'on", "Каттакурган"],
  ["samarqand-sh", "samarqand", "sh", "Samarqand", "Самарканд"],
  ["chiroqchi", "qashqadaryo", "t", "Chiroqchi", "Чиракчи"],
  ["dehqonobod", "qashqadaryo", "t", "Dehqonobod", "Дехканабад"],
  ["guzor", "qashqadaryo", "t", "G'uzor", "Гузар"],
  ["kasbi", "qashqadaryo", "t", "Kasbi", "Касби"],
  ["kitob", "qashqadaryo", "t", "Kitob", "Китаб"],
  ["koson", "qashqadaryo", "t", "Koson", "Касан"],
  ["kokdala", "qashqadaryo", "t", "Ko'kdala", "Кукдала"],
  ["mirishkor", "qashqadaryo", "t", "Mirishkor", "Миришкор"],
  ["muborak", "qashqadaryo", "t", "Muborak", "Мубарек"],
  ["nishon", "qashqadaryo", "t", "Nishon", "Нишан"],
  ["qamashi", "qashqadaryo", "t", "Qamashi", "Камаши"],
  ["qarshi", "qashqadaryo", "t", "Qarshi", "Карши"],
  ["shahrisabz", "qashqadaryo", "t", "Shahrisabz", "Шахрисабз"],
  ["yakkabog", "qashqadaryo", "t", "Yakkabog'", "Яккабаг"],
  ["qarshi-sh", "qashqadaryo", "sh", "Qarshi", "Карши"],
  ["shahrisabz-sh", "qashqadaryo", "sh", "Shahrisabz", "Шахрисабз"],
  ["angor", "surxondaryo", "t", "Angor", "Ангор"],
  ["bandixon", "surxondaryo", "t", "Bandixon", "Бандихан"],
  ["boysun", "surxondaryo", "t", "Boysun", "Байсун"],
  ["denov", "surxondaryo", "t", "Denov", "Денау"],
  ["jarqorgon", "surxondaryo", "t", "Jarqo'rg'on", "Джаркурган"],
  ["muzrabot", "surxondaryo", "t", "Muzrabot", "Музрабад"],
  ["oltinsoy", "surxondaryo", "t", "Oltinsoy", "Алтынсай"],
  ["qiziriq", "surxondaryo", "t", "Qiziriq", "Кизирик"],
  ["qumqorgon", "surxondaryo", "t", "Qumqo'rg'on", "Кумкурган"],
  ["sariosiyo", "surxondaryo", "t", "Sariosiyo", "Сариасия"],
  ["sherobod", "surxondaryo", "t", "Sherobod", "Шерабад"],
  ["shorchi", "surxondaryo", "t", "Sho'rchi", "Шурчи"],
  ["termiz", "surxondaryo", "t", "Termiz", "Термез"],
  ["uzun", "surxondaryo", "t", "Uzun", "Узун"],
  ["termiz-sh", "surxondaryo", "sh", "Termiz", "Термез"],
  ["buxoro", "buxoro", "t", "Buxoro", "Бухара"],
  ["gijduvon", "buxoro", "t", "G'ijduvon", "Гиждуван"],
  ["jondor", "buxoro", "t", "Jondor", "Жондор"],
  ["kogon", "buxoro", "t", "Kogon", "Каган"],
  ["olot", "buxoro", "t", "Olot", "Алат"],
  ["peshku", "buxoro", "t", "Peshku", "Пешку"],
  ["qorakol", "buxoro", "t", "Qorako'l", "Каракуль"],
  ["qorovulbozor", "buxoro", "t", "Qorovulbozor", "Караулбазар"],
  ["romitan", "buxoro", "t", "Romitan", "Ромитан"],
  ["shofirkon", "buxoro", "t", "Shofirkon", "Шафиркан"],
  ["vobkent", "buxoro", "t", "Vobkent", "Вабкент"],
  ["buxoro-sh", "buxoro", "sh", "Buxoro", "Бухара"],
  ["kogon-sh", "buxoro", "sh", "Kogon", "Каган"],
  ["karmana", "navoiy", "t", "Karmana", "Кармана"],
  ["konimex", "navoiy", "t", "Konimex", "Канимех"],
  ["navbahor", "navoiy", "t", "Navbahor", "Навбахор"],
  ["nurota", "navoiy", "t", "Nurota", "Нурата"],
  ["qiziltepa", "navoiy", "t", "Qiziltepa", "Кызылтепа"],
  ["tomdi", "navoiy", "t", "Tomdi", "Тамды"],
  ["uchquduq", "navoiy", "t", "Uchquduq", "Учкудук"],
  ["xatirchi", "navoiy", "t", "Xatirchi", "Хатырчи"],
  ["gozgon-sh", "navoiy", "sh", "G'ozg'on", "Газган"],
  ["navoiy-sh", "navoiy", "sh", "Navoiy", "Навои"],
  ["zarafshon-sh", "navoiy", "sh", "Zarafshon", "Зарафшан"],
  ["bogot", "xorazm", "t", "Bog'ot", "Багат"],
  ["gurlan", "xorazm", "t", "Gurlan", "Гурлен"],
  ["hazorasp", "xorazm", "t", "Hazorasp", "Хазарасп"],
  ["qoshkopir", "xorazm", "t", "Qo'shko'pir", "Кошкупыр"],
  ["shovot", "xorazm", "t", "Shovot", "Шават"],
  ["tuproqqala", "xorazm", "t", "Tuproqqal'a", "Тупроккала"],
  ["urganch", "xorazm", "t", "Urganch", "Ургенч"],
  ["xiva", "xorazm", "t", "Xiva", "Хива"],
  ["xonqa", "xorazm", "t", "Xonqa", "Ханка"],
  ["yangiariq", "xorazm", "t", "Yangiariq", "Янгиарык"],
  ["yangibozor", "xorazm", "t", "Yangibozor", "Янгибазар"],
  ["urganch-sh", "xorazm", "sh", "Urganch", "Ургенч"],
  ["xiva-sh", "xorazm", "sh", "Xiva", "Хива"],
  ["amudaryo", "qoraqalpogiston", "t", "Amudaryo", "Амударья"],
  ["beruniy", "qoraqalpogiston", "t", "Beruniy", "Беруни"],
  ["bozatov", "qoraqalpogiston", "t", "Bo'zatov", "Бозатау"],
  ["chimboy", "qoraqalpogiston", "t", "Chimboy", "Чимбай"],
  ["ellikqala", "qoraqalpogiston", "t", "Ellikqal'a", "Элликкала"],
  ["kegeyli", "qoraqalpogiston", "t", "Kegeyli", "Кегейли"],
  ["moynoq", "qoraqalpogiston", "t", "Mo'ynoq", "Муйнак"],
  ["nukus", "qoraqalpogiston", "t", "Nukus", "Нукус"],
  ["qanlikol", "qoraqalpogiston", "t", "Qanliko'l", "Канлыкуль"],
  ["qongirot", "qoraqalpogiston", "t", "Qo'ng'irot", "Кунград"],
  ["qoraozak", "qoraqalpogiston", "t", "Qorao'zak", "Караузяк"],
  ["shumanay", "qoraqalpogiston", "t", "Shumanay", "Шуманай"],
  ["taxiatosh", "qoraqalpogiston", "t", "Taxiatosh", "Тахиаташ"],
  ["taxtakopir", "qoraqalpogiston", "t", "Taxtako'pir", "Тахтакупыр"],
  ["tortkol", "qoraqalpogiston", "t", "To'rtko'l", "Турткуль"],
  ["xojayli", "qoraqalpogiston", "t", "Xo'jayli", "Ходжейли"],
  ["nukus-sh", "qoraqalpogiston", "sh", "Nukus", "Нукус"],
];

export type DistrictOption = { code: string; name: string; city: boolean };

export function districtOptions(region: string, locale: Locale): DistrictOption[] {
  return DISTRICTS.filter((row) => row[1] === region).map((row) => ({
    code: row[0],
    name: CYRILLIC.includes(locale) ? row[4] : row[3],
    city: row[2] === "sh",
  }));
}

export function districtName(code: string, locale: Locale): string {
  const row = DISTRICTS.find((r) => r[0] === code);
  if (!row) return code;
  return CYRILLIC.includes(locale) ? row[4] : row[3];
}
