# Generated by Django 5.2.17 on 2026-09-06 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_items', to='quizzes.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArenaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('seconds_per_question', models.PositiveIntegerField(default=60)),
                ('reward_qvant', models.PositiveIntegerField(default=15)),
                ('is_public', models.BooleanField(default=True)),
                ('rewards_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='arena_rounds', through='arena.ArenaQuestion', to='quizzes.question')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddField(
            model_name='arenaquestion',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arena.arenaround'),
        ),
        migrations.CreateModel(
            name='ArenaParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_ms', models.PositiveBigIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_runs', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='arena.arenaround')),
            ],
            options={
                'ordering': ['-score', 'total_ms', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('elapsed_ms', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='arena.arenaparticipation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participation', 'question'), name='uniq_arena_answer_once')],
            },
        ),
        migrations.AddConstraint(
            model_name='arenaquestion',
            constraint=models.UniqueConstraint(fields=('round', 'order'), name='uniq_arena_question_order'),
        ),
        migrations.AddConstraint(
            model_name='arenaquestion',
            constraint=models.UniqueConstraint(fields=('round', 'question'), name='uniq_arena_question'),
        ),
        migrations.AddConstraint(
            model_name='arenaparticipation',
            constraint=models.UniqueConstraint(fields=('round', 'user'), name='uniq_arena_participant'),
        ),
    ]
